const { SlashCommandBuilder } = require('discord.js');
const https = require('https');
import { savePokemonCatch } from '../services/pokemonService';
// const
const SHINY_RATE = 0.005;
// add ifaces
interface WikiSearchResult {
  query?: {
    search?: Array<{ pageid: number }>;
  };
}

interface WikiPageResult {
  query: {
    pages: {
      [key: string]: {
        original?: {
          source: string;
        };
        thumbnail?: {
          source: string;
        };
      };
    };
  };
}

interface PokeAPIResponse {
  name: string;
  sprites: {
    other: {
      'official-artwork': {
        front_default: string | null;
		front_shiny: string | null;
      };
    };
  };
}

const pokemonList = [
    6, //charizard
    12, //butterfree
    16, //pidgey
    17, //pidgeotto
    18, //pidgeot
    21, //spearow
    22, //fearow
    36, //clefable
    41, //zubat
    42, //golbat
    83, //farfetch'd
    84, //doduo
    85, //dodrio
    123, //scyther
    127, //pinsir
    130, //gyarados
    142, //aerodactyl
    144, //articuno
    145, //zapdos
    146, //moltres
    149, //dragonite
    163, //hoothoot
    164, //noctowl
    165, //ledyba
    166, //ledian
    169, //crobat
    176, //togetic
    177, //natu
    178, //xatu
    187, //hoppip
    188, //skiploom
    189, //jumpluff
    193, //yanma
    198, //murkrow
    207, //gligar
    225, //delibird
    226, //mantine
    227, //skarmory
    249, //lugia
    250, //ho-oh
    267, //beautifly
    276, //taillow
    277, //swellow
    278, //wingull
    279, //pelipper
    284, //masquerain
    291, //ninjask
    333, //swablu
    334, //altaria
    357, //tropius
    373, //salamence
    384, //rayquaza
    396, //starly
    397, //staravia
    398, //staraptor
    414, //mothim
    415, //combee
    416, //vespiquen
    425, //drifloon
    426, //drifblim
    430, //honchkrow
    441, //chatot
    458, //mantyke
    468, //togekiss
    469, //yanmega
    472, //gliscor
    479, //rotom
    492, //shaymin
    493, //arceus
    519, //pidove
    520, //tranquill
    521, //unfezant
    527, //woobat
    528, //swoobat
    561, //sigilyph
    566, //archen
    567, //archeops
    580, //ducklett
    581, //swanna
    587, //emolga
    627, //rufflet
    628, //braviary
    629, //vullaby
    630, //mandibuzz
    641, //tornadus
    642, //thundurus
    645, //landorus
    661, //fletchling
    662, //fletchinder
    663, //talonflame
    666, //vivillon
    701, //hawlucha
    714, //noibat
    715, //noivern
    717, //yveltal
    722, //rowlet
    723, //dartrix
    731, //pikipek
    732, //trumbeak
    733, //toucannon
    741, //oricorio
    773, //silvally
    774, //minior
    797, //celesteela
    821, //rookidee
    822, //corvisquire
    823, //corviknight
    845, //cramorant
    905, //enamorus
    931, //squawkabilly
    940, //wattrel
    941, //kilowattrel
    962, //bombirdier
    973, //flamigo
    993, //iron

]

const birdList = [
"Highland tinamou",
"Great tinamou",
"Little tinamou",
"Thicket tinamou",
"Slaty-breasted tinamou",
"Choco tinamou",
"Horned screamer",
"Northern screamer",
"American black duck",
"American wigeon",
"Baikal teal",
"Barnacle goose",
"Barrow's goldeneye",
"Black scoter",
"Black-bellied whistling-duck",
"Blue-winged teal",
"Brant",
"Bufflehead",
"Cackling goose",
"Canada goose",
"Canvasback",
"Cinnamon teal",
"Comb duck",
"Common eider",
"Common goldeneye",
"Common merganser",
"Common pochard",
"Common scoter",
"Common shelduck",
"Eastern spot-billed duck",
"Egyptian goose",
"Emperor goose",
"Eurasian wigeon",
"Falcated duck",
"Fulvous whistling-duck",
"Gadwall",
"Garganey",
"Graylag goose",
"Greater scaup",
"Greater white-fronted goose",
"Green-winged teal",
"Harlequin duck",
"Hooded merganser",
"King eider",
"Labrador duck",
"Lesser scaup",
"Lesser white-fronted goose",
"Long-tailed duck",
"Mallard",
"Masked duck",
"Mexican duck",
"Mottled duck",
"Muscovy duck",
"Mute swan",
"Northern pintail",
"Northern shoveler",
"Orinoco goose",
"Pink-footed goose",
"Red-breasted merganser",
"Redhead",
"Ring-necked duck",
"Ross's goose",
"Ruddy duck",
"Ruddy shelduck",
"Smew",
"Snow goose",
"Southern pochard",
"Spectacled eider",
"Stejneger's scoter",
"Steller's eider",
"Surf scoter",
"Taiga bean-goose",
"Trumpeter swan",
"Tufted duck",
"Tundra bean-goose",
"Tundra swan",
"Velvet scoter",
"West Indian whistling-duck",
"White-cheeked pintail",
"White-faced whistling-duck",
"White-winged scoter",
"Whooper swan",
"Wood duck",
"Baudo guan",
"Black guan",
"Crested guan",
"Gray-headed chachalaca",
"Great curassow",
"Highland guan",
"Horned guan",
"Plain chachalaca",
"Rufous-bellied chachalaca",
"Rufous-vented chachalaca",
"Trinidad piping guan",
"West Mexican chachalaca",
"White-bellied chachalaca",
"Helmeted guineafowl",
"Banded quail",
"Bearded wood-partridge",
"Black-breasted wood-quail",
"Black-eared wood-quail",
"Black-throated bobwhite",
"Buffy-crowned wood-partridge",
"California quail",
"Crested bobwhite",
"Elegant quail",
"Gambel's quail",
"Long-tailed wood-partridge",
"Marbled wood-quail",
"Montezuma quail",
"Mountain quail",
"Northern bobwhite",
"Ocellated quail",
"Scaled quail",
"Singing quail",
"Spotted wood-quail",
"Tacarcuna wood-quail",
"Tawny-faced quail",
"Chukar",
"Dusky grouse",
"Gray partridge",
"Greater prairie-chicken",
"Greater sage-grouse",
"Gunnison sage-grouse",
"Himalayan snowcock",
"Indian peafowl",
"Lesser prairie-chicken",
"Ocellated turkey",
"Red junglefowl",
"Ring-necked pheasant",
"Rock ptarmigan",
"Ruffed grouse",
"Sharp-tailed grouse",
"Sooty grouse",
"Spruce grouse",
"White-tailed ptarmigan",
"Wild turkey",
"Willow ptarmigan",
"American flamingo",
"Atitlan grebe",
"Eared grebe",
"Clark's grebe",
"Horned grebe",
"Least grebe",
"Pied-billed grebe",
"Red-necked grebe",
"Western grebe",
"African collared-dove",
"Band-tailed pigeon",
"Blue ground dove",
"Blue-headed quail-dove",
"Bridled quail-dove",
"Buff-fronted quail-dove",
"Caribbean dove",
"Chiriqui quail-dove",
"Common ground dove",
"Common wood pigeon",
"Crested quail-dove",
"Dusky pigeon",
"Eared dove",
"Eurasian collared-dove",
"European turtle-dove",
"Gray-chested dove",
"Gray-fronted quail-dove",
"Gray-fronted dove",
"Gray-headed dove",
"Grenada dove",
"Inca dove",
"Key West quail-dove",
"Maroon-chested ground dove",
"Mourning dove",
"Olive-backed quail-dove",
"Oriental turtle-dove",
"Pale-vented pigeon",
"Passenger pigeon",
"Plain pigeon",
"Plain-breasted ground dove",
"Plumbeous pigeon",
"Purplish-backed quail-dove",
"Red-billed pigeon",
"Ring-tailed pigeon",
"Rock pigeon",
"Ruddy ground dove",
"Ruddy pigeon",
"Ruddy quail-dove",
"Russet-crowned quail-dove",
"Scaled pigeon",
"Scaly-naped pigeon",
"Short-billed pigeon",
"Socorro dove",
"Spotted dove",
"Tuxtla quail-dove",
"Violaceous quail-dove",
"White-crowned pigeon",
"White-faced quail-dove",
"White-fronted quail-dove",
"White-tipped dove",
"White-winged dove",
"Zenaida dove",
"Chestnut-bellied sandgrouse",
"Antillean nighthawk",
"Buff-collared nightjar",
"Chuck-will's-widow",
"Common nighthawk",
"Common pauraque",
"Common poorwill",
"Cuban nightjar",
"Dusky nightjar",
"Eared poorwill",
"Eastern whip-poor-will",
"Gray nightjar",
"Hispaniolan nightjar",
"Jamaican pauraque",
"Least pauraque",
"Lesser nighthawk",
"Mexican whip-poor-will",
"Nacunda nighthawk",
"Ocellated poorwill",
"Puerto Rican nightjar",
"Rufous nightjar",
"Short-tailed nighthawk",
"Spot-tailed nightjar",
"Tawny-collared nightjar",
"White-tailed nightjar",
"Yucatan nightjar",
"Yucatan poorwill",
"Oilbird",
"Common potoo",
"Great potoo",
"Northern potoo",
"Alpine swift",
"Black swift",
"Antillean palm-swift",
"Band-rumped swift",
"Chapman's swift",
"Chestnut-collared swift",
"Chimney swift",
"Common swift",
"Costa Rican swift",
"Fork-tailed palm swift",
"Gray-rumped swift",
"Great swallow-tailed swift",
"Lesser Antillean swift",
"Lesser swallow-tailed swift",
"Little swift",
"Fork-tailed swift",
"Short-tailed swift",
"Sick's swift",
"Spot-fronted swift",
"Vaux's swift",
"White-chinned swift",
"White-collared swift",
"White-fronted swift",
"White-naped swift",
"White-throated needletail",
"White-throated swift",
"Allen's hummingbird",
"Amazilia hummingbird",
"Amethyst-throated hummingbird",
"Amethyst woodstar",
"Anna's hummingbird",
"Antillean crested hummingbird",
"Azure-crowned hummingbird",
"Bahama woodstar",
"Band-tailed barbthroat",
"Beautiful hummingbird",
"Bee hummingbird",
"Berylline hummingbird",
"Black-bellied hummingbird",
"Black-billed streamertail",
"Black-chinned hummingbird",
"Black-crested coquette",
"Black-throated mango",
"Blue-capped hummingbird",
"Blue-chested hummingbird",
"Blue-chinned sapphire",
"Blue-headed hummingbird",
"Blue-tailed hummingbird",
"Blue-tailed emerald",
"Blue-throated goldentail",
"Blue-throated hummingbird",
"Blue-vented hummingbird",
"Brace's emerald",
"Broad-billed hummingbird",
"Broad-tailed hummingbird",
"Bronze-tailed plumeleteer",
"Bronzy hermit",
"Brown violetear",
"Buff-bellied hummingbird",
"Bumblebee hummingbird",
"Calliope hummingbird",
"Canivet's emerald",
"Charming hummingbird",
"Cinnamon hummingbird",
"Coppery-headed emerald",
"Copper-rumped hummingbird",
"Costa's hummingbird",
"Cozumel emerald",
"Crowned woodnymph",
"Cuban emerald",
"Dusky hummingbird",
"Emerald-chinned hummingbird",
"Fiery-throated hummingbird",
"Garden emerald",
"Garnet-throated hummingbird",
"Glow-throated hummingbird",
"Golden-crowned emerald",
"Green hermit",
"Green mango",
"Green thorntail",
"Green-breasted mango",
"Green-breasted mountain-gem",
"Green-crowned brilliant",
"Green-fronted hummingbird",
"Green-fronted lancebill",
"Greenish puffleg",
"Green-throated carib",
"Green-throated mango",
"Green-throated mountain-gem",
"Hispaniolan emerald",
"Hispaniolan mango",
"Honduran emerald",
"Humboldt's sapphire",
"Inagua woodstar",
"Jamaican mango",
"Lesser violetear",
"Little hermit",
"Long-billed hermit",
"Long-billed starthroat",
"Long-tailed sabrewing",
"Lucifer hummingbird",
"Magenta-throated woodstar",
"Mangrove hummingbird",
"Mexican hermit",
"Mexican sheartail",
"Mexican violetear",
"Mexican woodnymph",
"Pale-bellied hermit",
"Pirre hummingbird",
"Plain-capped starthroat",
"Puerto Rican emerald",
"Puerto Rican mango",
"Purple-crowned fairy",
"Purple-throated carib",
"Purple-throated mountain-gem",
"Purple-throated woodstar",
"Red-billed streamertail",
"Rivoli's hummingbird",
"Ruby-throated hummingbird",
"Ruby-topaz hummingbird",
"Rufous hummingbird",
"Rufous sabrewing",
"Rufous-shafted woodstar",
"Rufous-breasted hermit",
"Rufous-crested coquette",
"Rufous-tailed hummingbird",
"Sapphire-throated hummingbird",
"Scaly-breasted hummingbird",
"Scintillant hummingbird",
"Short-crested coquette",
"Slender sheartail",
"Snowcap",
"Snowy-bellied hummingbird",
"Sparkling-tailed hummingbird",
"Stripe-tailed hummingbird",
"Stripe-throated hermit",
"Talamanca hummingbird",
"Tooth-billed hummingbird",
"Tufted coquette",
"Tres Marias hummingbird",
"Turquoise-crowned hummingbird",
"Veraguan mango",
"Vervain hummingbird",
"Violet sabrewing",
"Violet-bellied hummingbird",
"Violet-capped hummingbird",
"Violet-crowned hummingbird",
"Violet-headed hummingbird",
"Volcano hummingbird",
"Wedge-tailed sabrewing",
"White-bellied emerald",
"White-bellied mountain-gem",
"White-chested emerald",
"White-crested coquette",
"White-eared hummingbird",
"White-necked jacobin",
"White-tailed emerald",
"White-tailed goldenthroat",
"White-tailed hummingbird",
"White-tailed sabrewing",
"White-throated mountain-gem",
"White-tipped sicklebill",
"White-vented plumeleteer",
"Wine-throated hummingbird",
"Xantus's hummingbird",
"American coot",
"Purple gallinule",
"Ash-throated crake",
"Aztec rail",
"Azure gallinule",
"Black rail",
"Clapper rail",
"Colombian crake",
"Common gallinule",
"Common moorhen",
"Corn crake",
"Eurasian coot",
"Gray-breasted crake",
"Gray-cowled wood-rail",
"King rail",
"Mangrove rail",
"Ocellated crake",
"Paint-billed crake",
"Ridgway's rail",
"Ruddy crake",
"Rufous-necked wood-rail",
"Russet-naped wood-rail",
"Sora",
"Spotted crake",
"Spotted rail",
"Uniform crake",
"Virginia rail",
"Purple swamphen",
"Western water-rail",
"White-throated crake",
"Yellow rail",
"Yellow-breasted crake",
"Zapata rail",
"Sungrebe",
"Limpkin",
"Common crane",
"Hooded crane",
"Sandhill crane",
"Whooping crane",
"Double-striped thick-knee",
"American avocet",
"Black-winged stilt",
"Black-necked stilt",
"American oystercatcher",
"Black oystercatcher",
"Eurasian oystercatcher",
"American golden-plover",
"Black-bellied plover",
"Collared plover",
"Common ringed plover",
"Eurasian dotterel",
"European golden-plover",
"Greater sand plover",
"Killdeer",
"Lesser sand plover",
"Little ringed plover",
"Mountain plover",
"Northern lapwing",
"Oriental plover",
"Pacific golden-plover",
"Piping plover",
"Semipalmated plover",
"Snowy plover",
"Southern lapwing",
"Wilson's plover",
"Northern jacana",
"Wattled jacana",
"American woodcock",
"Baird's sandpiper",
"Bar-tailed godwit",
"Black turnstone",
"Black-tailed godwit",
"Bristle-thighed curlew",
"Broad-billed sandpiper",
"Buff-breasted sandpiper",
"Common greenshank",
"Common redshank",
"Common sandpiper",
"Common snipe",
"Curlew sandpiper",
"Dunlin",
"Eskimo curlew",
"Eurasian curlew",
"Eurasian woodcock",
"Far Eastern curlew",
"Great knot",
"Greater yellowlegs",
"Green sandpiper",
"Gray-tailed tattler",
"Hudsonian godwit",
"Whimbrel",
"Jack snipe",
"Least sandpiper",
"Lesser yellowlegs",
"Little curlew",
"Little stint",
"Long-billed curlew",
"Long-billed dowitcher",
"Long-toed stint",
"Marbled godwit",
"Marsh sandpiper",
"Pectoral sandpiper",
"Pin-tailed snipe",
"Purple sandpiper",
"Red knot",
"Red phalarope",
"Red-necked phalarope",
"Red-necked stint",
"Rock sandpiper",
"Ruddy turnstone",
"Ruff",
"Sanderling",
"Semipalmated sandpiper",
"Sharp-tailed sandpiper",
"Short-billed dowitcher",
"Slender-billed curlew",
"Solitary sandpiper",
"Solitary snipe",
"Spoon-billed sandpiper",
"Spotted redshank",
"Spotted sandpiper",
"Stilt sandpiper",
"Surfbird",
"Temminck's stint",
"Terek sandpiper",
"Upland sandpiper",
"Wandering tattler",
"Western sandpiper",
"White-rumped sandpiper",
"Willet",
"Wilson's phalarope",
"Wilson's snipe",
"Wood sandpiper",
"Collared pratincole",
"Oriental pratincole",
"Great skua",
"Long-tailed jaeger",
"Pomarine jaeger",
"Parasitic jaeger",
"South polar skua",
"Ancient murrelet",
"Atlantic puffin",
"Black guillemot",
"Cassin's auklet",
"Common murre",
"Craveri's murrelet",
"Crested auklet",
"Dovekie",
"Great auk",
"Guadalupe murrelet",
"Horned puffin",
"Kittlitz's murrelet",
"Least auklet",
"Long-billed murrelet",
"Marbled murrelet",
"Parakeet auklet",
"Pigeon guillemot",
"Razorbill",
"Rhinoceros auklet",
"Scripps's murrelet",
"Thick-billed murre",
"Tufted puffin",
"Whiskered auklet",
"Aleutian tern",
"Herring gull",
"Arctic tern",
"Belcher's gull",
"Black noddy",
"Black skimmer",
"Black tern",
"Black-headed gull",
"Black-legged kittiwake",
"Black-tailed gull",
"Bonaparte's gull",
"Bridled tern",
"Brown noddy",
"California gull",
"Caspian tern",
"Common gull",
"Common tern",
"Elegant tern",
"Forster's tern",
"Franklin's gull",
"Glaucous gull",
"Glaucous-winged gull",
"Gray gull",
"Great black-backed gull",
"Gray-hooded gull",
"Gull-billed tern",
"Heermann's gull",
"Iceland gull",
"Inca tern",
"Ivory gull",
"Kelp gull",
"Large-billed tern",
"Laughing gull",
"Least tern",
"Lesser black-backed gull",
"Little gull",
"Pallas's gull",
"Red-legged kittiwake",
"Ring-billed gull",
"Roseate tern",
"Ross's gull",
"Royal tern",
"Sabine's gull",
"Sandwich tern",
"Short-billed gull",
"Slaty-backed gull",
"Sooty tern",
"Swallow-tailed gull",
"Western gull",
"Whiskered tern",
"White tern",
"White-winged tern",
"Yellow-billed tern",
"Yellow-footed gull",
"Yellow-legged gull",
"Sunbittern",
"Red-billed tropicbird",
"Red-tailed tropicbird",
"White-tailed tropicbird",
"Galapagos Penguin",
"Magellanic Penguin",
"African Penguin",
"Northern Rockhopper Penguin",
"King Penguin",
"Adelie Penguin",
"Fairy Penguin",
"Yellow-Eyed Penguin",
"Chinstrap Penguin",
"Southern Rockhopper Penguin",
"Macaroni Penguin",
"Australian Little Penguin",
"Emperor Penguin",
"Snares Penguin",
"Royal Penguin",
"Humboldt Penguin",
"Eastern Rockhopper Penguin",
"Fiordland Penguin",
"Allied King Penguin",
"Arctic loon",
"Common loon",
"Pacific loon",
"Red-throated loon",
"Yellow-billed loon",
"Yellow-nosed albatross",
"Black-browed albatross",
"Black-footed albatross",
"Chatham albatross",
"Laysan albatross",
"Light-mantled albatross",
"Salvin's albatross",
"Short-tailed albatross",
"White-capped albatross",
"Wandering albatross",
"Waved albatross",
"Black-bellied storm-petrel",
"White-faced storm-petrel",
"Wilson's storm-petrel",
"Ainley's storm-petrel",
"Ashy storm-petrel",
"Band-rumped storm-petrel",
"Black storm-petrel",
"European storm-petrel",
"Fork-tailed storm-petrel",
"Guadalupe storm-petrel",
"Leach's storm-petrel",
"Least storm-petrel",
"Markham's storm-petrel",
"Ringed storm-petrel",
"Swinhoe's storm-petrel",
"Townsend's storm-petrel",
"Tristram's storm-petrel",
"Wedge-rumped storm-petrel",
"Sargasso shearwater",
"Barolo shearwater",
"Bermuda petrel",
"Black-capped petrel",
"Black-vented shearwater",
"Buller's shearwater",
"Bulwer's petrel",
"Cape Verde shearwater",
"Christmas shearwater",
"Cook's petrel",
"Cory's shearwater",
"Fea's petrel",
"Flesh-footed shearwater",
"Galapagos petrel",
"Galapagos shearwater",
"Gray-faced petrel",
"Great shearwater",
"Hawaiian petrel",
"Herald petrel",
"Jamaican petrel",
"Juan Fernandez petrel",
"Kermadec petrel",
"Manx shearwater",
"Mottled petrel",
"Murphy's petrel",
"Newell's shearwater",
"Northern fulmar",
"Northern giant-petrel",
"Parkinson's petrel",
"Pink-footed shearwater",
"Providence petrel",
"Short-tailed shearwater",
"Sooty shearwater",
"Stejneger's petrel",
"Streaked shearwater",
"Tahiti petrel",
"Townsend's shearwater",
"Trindade petrel",
"Wedge-tailed shearwater,",
"White-chinned petrel",
"Zino's petrel",
"Jabiru",
"Maguari stork",
"White stork",
"Wood stork",
"Great frigatebird",
"Lesser frigatebird",
"Magnificent frigatebird",
"Blue-footed booby",
"Brown booby",
"Masked booby",
"Nazca booby",
"Northern gannet",
"Peruvian booby",
"Red-footed booby",
"Anhinga",
"Brandt's cormorant",
"Double-crested cormorant",
"Great cormorant",
"Guanay cormorant",
"Neotropic cormorant",
"Pelagic cormorant",
"Red-faced cormorant",
"American white pelican",
"Brown pelican",
"Great white pelican",
"Peruvian pelican",
"Agami heron",
"American bittern",
"Bare-throated tiger-heron",
"Black-crowned night-heron",
"Boat-billed heron",
"Capped heron",
"Cattle egret",
"Chinese egret",
"Chinese pond-heron",
"Cocoi heron",
"Fasciated tiger-heron",
"Gray heron",
"Great blue heron",
"Great egret",
"Green heron",
"Intermediate egret",
"Least bittern",
"Little bittern",
"Little blue heron",
"Little egret",
"Pinnated bittern",
"Purple heron",
"Reddish egret",
"Rufescent tiger-heron",
"Snowy egret",
"Squacco heron",
"Striated heron",
"Stripe-backed bittern",
"Tricolored heron",
"Western reef-heron",
"Whistling heron",
"Yellow bittern,",
"Yellow-crowned night-heron",
"African sacred ibis",
"White ibis",
"Bare-faced ibis",
"Buff-necked ibis",
"Eurasian spoonbill",
"Glossy ibis",
"Green ibis",
"Roseate spoonbill",
"Scarlet ibis",
"White-faced ibis",
"Black vulture",
"California condor",
"King vulture",
"Lesser yellow-headed vulture",
"Turkey vulture",
"Osprey",
"Bald eagle",
"Barred hawk",
"Bicolored hawk",
"Black hawk-eagle",
"Black kite",
"Black-and-white hawk-eagle",
"Black-collared hawk",
"Booted eagle",
"Broad-winged hawk",
"Chinese sparrowhawk",
"Common black hawk",
"Cooper's hawk",
"Crane hawk",
"Crested eagle",
"Cuban black hawk",
"Cuban kite",
"Double-toothed kite",
"Eurasian sparrowhawk",
"Ferruginous hawk",
"Golden eagle",
"Great black hawk",
"Gray hawk",
"Gray-bellied hawk",
"Gray-headed kite",
"Gray-lined hawk",
"Gundlach's hawk",
"Harpy eagle",
"Harris's hawk",
"Hook-billed kite",
"Long-legged buzzard",
"Long-winged harrier",
"Mississippi kite",
"Eurasian goshawk",
"American goshawk",
"Northern harrier",
"Western marsh harrier",
"Ornate hawk-eagle",
"Pearl kite",
"Plumbeous hawk",
"Plumbeous kite",
"Red-shouldered hawk",
"Red-tailed hawk",
"Ridgway's hawk",
"Roadside hawk",
"Rough-legged hawk",
"Savanna hawk",
"Semiplumbeous hawk",
"Sharp-shinned hawk",
"Short-tailed hawk",
"Slender-billed kite",
"Snail kite",
"Solitary eagle",
"Steller's sea-eagle",
"Swainson's hawk",
"Swallow-tailed kite",
"Tiny hawk",
"White hawk",
"White-tailed eagle",
"White-tailed hawk",
"White-tailed kite",
"Zone-tailed hawk",
"Barn owl",
"Ashy-faced owl",
"Balsas screech-owl",
"Bare-legged owl",
"Bare-shanked screech-owl",
"Barred owl",
"Bearded screech-owl",
"Bermuda saw-whet owl",
"Black-and-white owl",
"Boreal owl",
"Burrowing owl",
"Central American pygmy-owl",
"Choco screech-owl",
"Cinereous owl",
"Colima pygmy-owl",
"Costa Rican pygmy-owl",
"Crested owl",
"Cuban pygmy-owl",
"Eastern screech-owl",
"Elf owl",
"Ferruginous pygmy-owl",
"Flammulated owl",
"Fulvous owl",
"Great gray owl",
"Great horned owl",
"Jamaican owl",
"Long-eared owl",
"Middle American screech-owl",
"Mottled owl",
"Northern boobook",
"Northern hawk owl",
"Northern pygmy-owl",
"Northern saw-whet owl",
"Oriental scops-owl",
"Pacific screech-owl",
"Puerto Rican owl",
"Short-eared owl",
"Snowy owl",
"Spectacled owl",
"Spotted owl",
"Striped owl",
"Stygian owl",
"Tamaulipas pygmy-owl",
"Tropical screech-owl",
"Unspotted saw-whet owl",
"Western screech-owl",
"Whiskered screech-owl",
"Baird's trogon",
"Black-headed trogon",
"Black-tailed trogon",
"Black-throated trogon",
"Citreoline trogon",
"Collared trogon",
"Cuban trogon",
"Eared quetzal",
"Elegant trogon",
"Gartered trogon",
"Golden-headed quetzal",
"Green-backed trogon",
"Guianan trogon",
"Hispaniolan trogon",
"Lattice-tailed trogon",
"Mountain trogon",
"Resplendent quetzal",
"Slaty-tailed trogon",
"White-tailed trogon",
"Eurasian hoopoe",
"Cuban tody",
"Broad-billed tody",
"Jamaican tody",
"Narrow-billed tody",
"Puerto Rican tody",
"Blue-capped motmot",
"Blue-throated motmot",
"Broad-billed motmot",
"Keel-billed motmot",
"Lesson's motmot",
"Rufous motmot",
"Russet-crowned motmot",
"Tody motmot",
"Trinidad motmot",
"Turquoise-browed motmot",
"Whooping motmot",
"Amazon kingfisher",
"American pygmy kingfisher",
"Belted kingfisher",
"Green kingfisher",
"Green-and-rufous kingfisher",
"Ringed kingfisher",
"European bee-eater",
"Barred puffbird",
"Black-breasted puffbird",
"Gray-cheeked nunlet",
"Lanceolated monklet",
"Pied puffbird",
"Russet-throated puffbird",
"White-fronted nunbird",
"White-necked puffbird",
"White-whiskered puffbird",
"Dusky-backed jacamar",
"Great jacamar",
"Rufous-tailed jacamar",
"Red-headed barbet",
"Spot-crowned barbet",
"Channel-billed toucan",
"Collared aracari",
"Fiery-billed aracari",
"Keel-billed toucan",
"Northern emerald-toucanet",
"Yellow-eared toucanet",
"Yellow-throated toucan",
"Prong-billed barbet",
"Acorn woodpecker",
"American three-toed woodpecker",
"Antillean piculet",
"Arizona woodpecker",
"Black-backed woodpecker",
"Black-cheeked woodpecker",
"Chestnut-colored woodpecker",
"Cinnamon woodpecker",
"Crimson-bellied woodpecker",
"Crimson-crested woodpecker",
"Cuban green woodpecker",
"Downy woodpecker",
"Eurasian wryneck",
"Fernandina's flicker",
"Gila woodpecker",
"Gilded flicker",
"Golden-cheeked woodpecker",
"Golden-fronted woodpecker",
"Golden-green woodpecker",
"Golden-naped woodpecker",
"Golden-olive woodpecker",
"Gray-breasted woodpecker",
"Great spotted woodpecker",
"Gray-crowned woodpecker",
"Guadeloupe woodpecker",
"Hairy woodpecker",
"Hispaniolan woodpecker",
"Hoffmann's woodpecker",
"Imperial woodpecker",
"Ivory-billed woodpecker",
"Jamaican woodpecker",
"Ladder-backed woodpecker",
"Lewis's woodpecker",
"Lineated woodpecker",
"Northern flicker",
"Nuttall's woodpecker",
"Olivaceous piculet",
"Pale-billed woodpecker",
"Pileated woodpecker",
"Puerto Rican woodpecker",
"Red-bellied woodpecker",
"Red-breasted sapsucker",
"Red-cockaded woodpecker",
"Red-crowned woodpecker",
"Red-headed woodpecker",
"Red-naped sapsucker",
"Red-rumped woodpecker",
"Rufous-winged woodpecker",
"Smoky-brown woodpecker",
"Spot-breasted woodpecker",
"Strickland's woodpecker",
"Stripe-cheeked woodpecker",
"West Indian woodpecker",
"White-headed woodpecker",
"Williamson's sapsucker",
"Yellow-bellied sapsucker",
"Yucatan woodpecker",
"American kestrel",
"Aplomado falcon",
"Barred forest-falcon",
"Bat falcon",
"Collared forest-falcon",
"Crested caracara",
"Eurasian hobby",
"Eurasian kestrel",
"Guadalupe caracara",
"Gyrfalcon",
"Laughing falcon",
"Merlin",
"Orange-breasted falcon",
"Peregrine falcon",
"Prairie falcon",
"Red-footed falcon",
"Red-throated caracara",
"Slaty-backed forest-falcon",
"Yellow-headed caracara",
"Barred parakeet",
"Black-billed parrot",
"Blue-and-yellow macaw",
"Blue-fronted parrotlet",
"Blue-headed parrot",
"Brown-hooded parrot",
"Brown-throated parakeet",
"Carolina parakeet",
"Chestnut-fronted macaw",
"Crimson-fronted parakeet",
"Cuban macaw",
"Cuban parakeet",
"Cuban parrot",
"Orange-fronted parakeet",
"Great green macaw",
"Green parakeet",
"Green-rumped parrotlet",
"Hispaniolan parakeet",
"Hispaniolan parrot",
"Imperial parrot",
"Lilac-crowned parrot",
"Lilac-tailed parrotlet",
"Maroon-fronted parrot",
"Mealy parrot",
"Mexican parrotlet",
"Military macaw",
"Mitred parakeet",
"Monk parakeet",
"Nanday parakeet",
"Olive-throated parakeet",
"Orange-chinned parakeet",
"Orange-winged parrot",
"Pacific parakeet",
"Painted parakeet",
"Puerto Rican parakeet",
"Puerto Rican parrot",
"Red-and-green macaw",
"Red-bellied macaw",
"Red-crowned parrot",
"Red-fronted parrotlet",
"Red-lored parrot",
"Red-necked parrot",
"Saffron-headed parrot",
"Scarlet macaw",
"Scarlet-shouldered parrotlet",
"Socorro parakeet",
"Spectacled parrotlet",
"St. Lucia parrot",
"St. Vincent parrot",
"Sulphur-winged parakeet",
"Thick-billed parrot",
"White-crowned parrot",
"White-eyed parakeet",
"White-fronted parrot",
"White-winged parakeet",
"Yellow-billed parrot",
"Yellow-chevroned parakeet",
"Yellow-crowned parrot",
"Yellow-headed parrot",
"Yellow-lored parrot",
"Yellow-naped parrot",
"Rose-ringed parakeet",
"Rosy-faced lovebird",
"Sapayoa",
"Bare-crowned antbird",
"Barred antshrike",
"Bicolored antbird",
"Black antshrike",
"Black-crested antshrike",
"Black-crowned antshrike",
"Black-hooded antshrike",
"Checker-throated stipplethroat",
"Chestnut-backed antbird",
"Dot-winged antwren",
"Dull-mantled antbird",
"Dusky antbird",
"Fasciated antshrike",
"Great antshrike",
"Jet antbird",
"Moustached antwren",
"Ocellated antbird",
"Pacific antwren",
"Plain antvireo",
"Rufous-rumped antwren",
"Rufous-winged antwren",
"Russet antshrike",
"Rusty-winged antwren",
"Slaty antwren",
"Spiny-faced antshrike",
"Spot-crowned antvireo",
"Spotted antbird",
"Streak-crowned antvireo",
"White-bellied antbird",
"White-flanked antwren",
"White-fringed antwren",
"Wing-banded antbird",
"Zeledon's antbird",
"Black-crowned antpitta",
"Ochre-breasted antpitta",
"Scaled antpitta",
"Streak-chested antpitta",
"Thicket antpitta",
"Choco tapaculo",
"Silvery-fronted tapaculo",
"Tacarcuna tapaculo",
"Black-faced antthrush",
"Black-headed antthrush",
"Mayan antthrush",
"Rufous-breasted antthrush",
"Beautiful treerunner",
"Black-banded woodcreeper",
"Black-striped woodcreeper",
"Brown-billed scythebill",
"Buff-fronted foliage-gleaner",
"Buff-throated foliage-gleaner",
"Buffy tufted cheek",
"Chiriqui foliage-gleaner",
"Cocoa woodcreeper",
"Coiba spinetail",
"Double-banded graytail",
"Gray-throated leaftosser",
"Ivory-billed woodcreeper",
"Lineated foliage-gleaner",
"Long-tailed woodcreeper",
"Northern barred-woodcreeper",
"Olivaceous woodcreeper",
"Pale-breasted spinetail",
"Plain xenops",
"Plain-brown woodcreeper",
"Red-billed scythebill",
"Red-faced spinetail",
"Ruddy foliage-gleaner",
"Ruddy treerunner",
"Ruddy woodcreeper",
"Rufous-breasted spinetail",
"Scaly-throated foliage-gleaner",
"Scaly-throated leaftosser",
"Sharp-tailed streamcreeper",
"Slaty spinetail",
"Slaty-winged foliage-gleaner",
"Spot-crowned woodcreeper",
"Spotted barbtail",
"Spotted woodcreeper",
"Straight-billed woodcreeper",
"Streak-breasted treehunter",
"Streaked xenops",
"Streak-headed woodcreeper",
"Striped woodhaunter",
"Strong-billed woodcreeper",
"Tawny-throated leaftosser",
"Tawny-winged woodcreeper",
"Wedge-billed woodcreeper",
"White-striped woodcreeper",
"Golden-collared manakin",
"Golden-headed manakin",
"Green manakin",
"Lance-tailed manakin",
"Long-tailed manakin",
"Orange-collared manakin",
"Red-capped manakin",
"Blue-crowned manakin",
"White-collared manakin",
"White-crowned manakin",
"White-ruffed manakin",
"Bare-necked umbrellabird",
"Bearded bellbird",
"Black-tipped cotinga",
"Blue cotinga",
"Lovely cotinga",
"Purple-throated fruitcrow",
"Rufous piha",
"Snowy cotinga",
"Three-wattled bellbird",
"Turquoise cotinga",
"White bellbird",
"Yellow-billed cotinga",
"Barred becard",
"Black-and-white becard",
"Black-crowned tityra",
"Black-tailed tityra",
"Cinereous becard",
"Cinnamon becard",
"Gray-collared becard",
"Jamaican becard",
"Masked tityra",
"Northern schiffornis",
"One-colored becard",
"Rose-throated becard",
"Russet-winged schiffornis",
"Speckled mourner",
"White-winged becard",
"Sharpbill",
"Black-tailed flycatcher",
"Royal flycatcher",
"Ruddy-tailed flycatcher",
"Sulphur-rumped flycatcher",
"Tawny-breasted flycatcher",
"Acadian flycatcher",
"Alder flycatcher",
"Dusky flycatcher",
"Gray flycatcher",
"Ash-throated flycatcher",
"Belted flycatcher",
"Black phoebe",
"Black-billed flycatcher",
"Black-capped flycatcher",
"Black-capped pygmy-tyrant",
"Black-headed tody-flycatcher",
"Blue Mountain elaenia",
"Boat-billed flycatcher",
"Bran-colored flycatcher",
"Bright-rumped attila",
"Bronze-olive pygmy-tyrant",
"Brown-capped tyrannulet",
"Brown-crested flycatcher",
"Brownish twistwing",
"Buff-breasted flycatcher",
"Caribbean elaenia",
"Cassin's kingbird",
"Cattle tyrant",
"Choco sirystes",
"Cocos flycatcher",
"Common tody-flycatcher",
"Couch's kingbird",
"Crowned slaty flycatcher",
"Cuban pewee",
"Dark pewee",
"Dusky-capped flycatcher",
"Eastern kingbird",
"Eastern phoebe",
"Eastern wood-pewee",
"Euler's flycatcher",
"Eye-ringed flatbill",
"Flammulated flycatcher",
"Forest elaenia",
"Fork-tailed flycatcher",
"Giant kingbird",
"Golden-bellied flycatcher",
"Golden-crowned flycatcher",
"Golden-crowned spadebill",
"Great crested flycatcher",
"Great kiskadee",
"Greater pewee",
"Greenish elaenia",
"Grenada flycatcher",
"Gray elaenia",
"Gray kingbird",
"Gray-capped flycatcher",
"Gray-headed piprites",
"Guatemalan tyrannulet",
"Hammond's flycatcher",
"Hispaniolan elaenia",
"Hispaniolan pewee",
"Jamaican elaenia",
"Jamaican pewee",
"La Sagra's flycatcher",
"Least flycatcher",
"Lesser Antillean flycatcher",
"Lesser Antillean pewee",
"Lesser elaenia",
"Lesser kiskadee",
"Loggerhead kingbird",
"Long-tailed tyrant",
"Mistletoe tyrannulet",
"Mountain elaenia",
"Mouse-colored tyrannulet",
"Northern beardless-tyrannulet",
"Northern bentbill",
"Northern scrub-flycatcher",
"Nutting's flycatcher",
"Ochraceous pewee",
"Ochre-bellied flycatcher",
"Olivaceous flatbill",
"Olive-sided flycatcher",
"Olive-striped flycatcher",
"Pale-eyed pygmy-tyrant",
"Panama flycatcher",
"Pied water-tyrant",
"Pileated flycatcher",
"Pine flycatcher",
"Piratic flycatcher",
"Puerto Rican flycatcher",
"Rufous mourner",
"Rufous-browed tyrannulet",
"Rufous-tailed flycatcher",
"Rusty-margined flycatcher",
"Sad flycatcher",
"Say's phoebe",
"Scale-crested pygmy-tyrant",
"Scissor-tailed flycatcher",
"Sepia-capped flycatcher",
"Slate-headed tody-flycatcher",
"Slaty-capped flycatcher",
"Small-billed elaenia",
"Social flycatcher",
"Sooty-headed tyrannulet",
"Southern beardless-tyrannulet",
"Southern bentbill",
"Stolid flycatcher",
"Streaked flycatcher",
"Stub-tailed spadebill",
"Sulphur-bellied flycatcher",
"Tawny-chested flycatcher",
"Thick-billed kingbird",
"Torrent tyrannulet",
"Tropical kingbird",
"Tropical pewee",
"Tufted flycatcher",
"Variegated flycatcher",
"Vermilion flycatcher",
"Western flycatcher",
"Western kingbird",
"Western wood-pewee",
"White-crested elaenia",
"Rough-legged tyrannulet",
"White-ringed flycatcher",
"White-throated flycatcher",
"White-throated spadebill",
"Willow flycatcher",
"Yellow tyrannulet",
"Yellow-bellied elaenia",
"Yellow-bellied flycatcher",
"Yellow-bellied tyrannulet",
"Yellow-breasted flycatcher",
"Yellow-crowned tyrannulet",
"Yellow-green tyrannulet",
"Yellowish flycatcher",
"Yellow-margined flycatcher",
"Yellow-olive flycatcher",
"Yucatan flycatcher",
"Brown shrike",
"Loggerhead shrike",
"Northern shrike",
"Red-backed shrike",
"Bell's vireo",
"Black-capped vireo",
"Black-whiskered vireo",
"Blue Mountain vireo",
"Blue-headed vireo",
"Brown-capped vireo",
"Cassin's vireo",
"Chestnut-sided shrike-vireo",
"Cozumel vireo",
"Cuban vireo",
"Dwarf vireo",
"Flat-billed vireo",
"Golden vireo",
"Golden-fronted greenlet",
"Gray vireo",
"Green shrike-vireo",
"Hutton's vireo",
"Jamaican vireo",
"Lesser greenlet",
"Mangrove vireo",
"Philadelphia vireo",
"Plumbeous vireo",
"Puerto Rican vireo",
"Red-eyed vireo",
"Rufous-browed peppershrike",
"San Andres vireo",
"Scrub greenlet",
"Slaty vireo",
"Tawny-crowned greenlet",
"Thick-billed vireo",
"Warbling vireo",
"White-eyed vireo",
"Yellow-browed shrike-vireo",
"Yellow-green vireo",
"Yellow-throated vireo",
"Yellow-winged vireo",
"Yucatan vireo",
"American crow",
"Azure-hooded jay",
"Black-billed magpie",
"Black-chested jay",
"Black-throated jay",
"Black-throated magpie-jay",
"Blue jay",
"Brown jay",
"Bushy-crested jay",
"California scrub-jay",
"Canada jay",
"Chihuahuan raven",
"Clark's nutcracker",
"Common raven",
"Cuban crow",
"Dwarf jay",
"Eurasian jackdaw",
"Fish crow",
"Florida scrub-jay",
"Green jay",
"Hooded crow",
"House crow",
"Island scrub-jay",
"Jamaican crow",
"Mexican jay",
"Palm crow",
"Pinyon jay",
"Purplish-backed jay",
"Rook",
"San Blas jay",
"Silvery-throated jay",
"Sinaloa crow",
"Steller's jay",
"Tamaulipas crow",
"Transvolcanic jay",
"Tufted jay",
"Unicolored jay",
"White-necked crow",
"White-throated jay",
"White-throated magpie-jay",
"Woodhouse's scrub-jay",
"Yellow-billed magpie",
"Yucatan jay",
"Eurasian skylark",
"Horned lark",
"Cliff swallow",
"Bahama swallow",
"Bank swallow",
"Barn swallow",
"Black-capped swallow",
"Blue-and-white swallow",
"Brown-chested martin",
"Caribbean martin",
"Cave swallow",
"Common house-martin",
"Cuban martin",
"Golden swallow",
"Gray-breasted martin",
"Mangrove swallow",
"Northern rough-winged swallow",
"Purple martin",
"Sinaloa martin",
"Southern martin",
"Southern rough-winged swallow",
"Tree swallow",
"Violet-green swallow",
"White-thighed swallow",
"Black-capped chickadee",
"Black-crested titmouse",
"Boreal chickadee",
"Bridled titmouse",
"Carolina chickadee",
"Chestnut-backed chickadee",
"Gray-headed chickadee",
"Juniper titmouse",
"Mexican chickadee",
"Mountain chickadee",
"Oak titmouse",
"Tufted titmouse",
"Verdin",
"Bushtit",
"Bahama nuthatch",
"Brown-headed nuthatch",
"Pygmy nuthatch",
"Red-breasted nuthatch",
"White-breasted nuthatch",
"Brown creeper",
"Band-backed wren",
"Banded wren",
"Bay wren",
"Bewick's wren",
"Bicolored wren",
"Black-bellied wren",
"Black-throated wren",
"Boucard's wren",
"Buff-breasted wren",
"Cabanis's wren",
"Cactus wren",
"Canebrake wren",
"Canyon wren",
"Carolina wren",
"Clarión wren",
"Giant wren",
"Grass wren",
"Gray-barred wren",
"Gray-breasted wood-wren",
"Happy wren",
"House wren",
"Isthmian wren",
"Marsh wren",
"Nava's wren",
"Nightingale wren",
"Ochraceous wren",
"Pacific wren",
"Riverside wren",
"Rock wren",
"Rufous-and-white wren",
"Rufous-breasted wren",
"Rufous-browed wren",
"Rufous-naped wren",
"Scaly-breasted wren",
"Sedge wren",
"Sinaloa wren",
"Socorro wren",
"Song wren",
"Sooty-headed wren",
"Spot-breasted wren",
"Spotted wren",
"Stripe-breasted wren",
"Stripe-throated wren",
"Sumichrast's wren",
"Timberline wren",
"White-bellied wren",
"White-breasted wood-wren",
"White-headed wren",
"Winter wren",
"Yucatan wren",
"Zapata wren",
"Black-capped gnatcatcher",
"Black-tailed gnatcatcher",
"Blue-gray gnatcatcher",
"California gnatcatcher",
"Cuban gnatcatcher",
"Long-billed gnatwren",
"Slate-throated gnatcatcher",
"Tawny-faced gnatwren",
"White-browed gnatcatcher",
"White-lored gnatcatcher",
"Yucatan gnatcatcher",
"American dipper",
"Red-whiskered bulbul",
"Golden-crowned kinglet",
"Ruby-crowned kinglet",
"Arctic warbler",
"Common chiffchaff",
"Dusky warbler",
"Kamchatka leaf warbler",
"Pallas's leaf warbler",
"Willow warbler",
"Wood warbler",
"Yellow-browed warbler",
"Eurasian blackcap",
"Lesser whitethroat",
"Wrentit",
"Blyth's reed warbler",
"Sedge warbler",
"Icterine warbler",
"Thick-billed warbler",
"Black-capped donacobius",
"Middendorff's grasshopper warbler",
"Pallas's grasshopper warbler",
"Lanceolated warbler",
"River warbler",
"Asian brown flycatcher",
"Bluethroat",
"Common redstart",
"Dark-sided flycatcher",
"European robin",
"Gray-streaked flycatcher",
"Mugimaki flycatcher",
"Narcissus flycatcher",
"Northern wheatear",
"Pied wheatear",
"Red-flanked bluetail",
"Rufous-tailed robin",
"Siberian blue robin",
"Siberian rubythroat",
"Siberian stonechat",
"Spotted flycatcher",
"Taiga flycatcher",
"American robin",
"Aztec thrush",
"Bicknell's thrush",
"Black thrush",
"Black-billed nightingale-thrush",
"Black-faced solitaire",
"Black-headed nightingale-thrush",
"Brown-backed solitaire",
"Clay-colored thrush",
"Cocoa thrush",
"Eurasian blackbird",
"Cuban solitaire",
"Dusky thrush",
"Eastern bluebird",
"Eyebrowed thrush",
"Fieldfare",
"Forest thrush",
"Grand Cayman thrush",
"Gray-cheeked thrush",
"Hermit thrush",
"La Selle thrush",
"Mistle Thrush",
"Mountain bluebird",
"Mountain thrush",
"Naumann's thrush",
"Orange-billed nightingale-thrush",
"Pale-vented thrush",
"Western red-legged thrush",
"Eastern red-legged thrush",
"Redwing",
"Ruddy-capped nightingale-thrush",
"Rufous-backed robin",
"Rufous-collared robin",
"Rufous-throated solitaire",
"Russet nightingale-thrush",
"Slate-colored solitaire",
"Slaty-backed nightingale-thrush",
"Song thrush",
"Sooty thrush",
"Spectacled thrush",
"Swainson's thrush",
"Townsend's solitaire",
"Varied solitaire",
"Varied thrush",
"Veery",
"Western bluebird",
"White-chinned thrush",
"White-eyed thrush",
"White's thrush",
"White-throated thrush",
"Wood thrush",
"Yellow-throated nightingale-thrush",
"Bahama mockingbird",
"Bendire's thrasher",
"Black catbird",
"Blue mockingbird",
"Blue-and-white mockingbird",
"Brown thrasher",
"Brown trembler",
"California thrasher",
"Cozumel thrasher",
"Crissal thrasher",
"Curve-billed thrasher",
"Gray catbird",
"Gray thrasher",
"Gray trembler",
"LeConte's thrasher",
"Long-billed thrasher",
"Northern mockingbird",
"Ocellated thrasher",
"Pearly-eyed thrasher",
"Sage thrasher",
"Scaly-breasted thrasher",
"Socorro mockingbird",
"Tropical mockingbird",
"White-breasted thrasher",
"European starling",
"Common myna",
"Bohemian waxwing",
"Cedar waxwing",
"Black-and-yellow silky-flycatcher",
"Gray silky-flycatcher",
"Long-tailed silky-flycatcher",
"Phainopepla",
"Palmchat",
"Olive warbler",
"Siberian accentor",
"Village weaver",
"Northern red bishop",
"Yellow-crowned bishop",
"Pin-tailed whydah",
"African silverbill",
"Black-rumped waxbill",
"Bronze mannikin",
"Chestnut munia",
"Common waxbill",
"Indian silverbill",
"Java sparrow",
"Orange-cheeked waxbill",
"Red avadavat",
"Scaly-breasted munia",
"Tricolored munia",
"Eurasian tree sparrow",
"House sparrow",
"American pipit",
"Citrine wagtail",
"Eastern yellow wagtail",
"Gray wagtail",
"Meadow pipit",
"Olive-backed pipit",
"Pechora pipit",
"Red-throated pipit",
"Sprague's pipit",
"Tree pipit",
"White wagtail",
"Yellowish pipit",
"American goldfinch",
"Antillean siskin",
"Asian rosy-finch",
"Island canary",
"Black rosy-finch",
"Black-capped siskin",
"Black-headed siskin",
"Blue-crowned chlorophonia",
"Brambling",
"Brown-capped rosy-finch",
"Cassia crossbill",
"Cassin's finch",
"Common chaffinch",
"Common redpoll",
"Common rosefinch",
"Elegant euphonia",
"Eurasian bullfinch",
"Eurasian siskin",
"European goldfinch",
"Evening grosbeak",
"Fulvous-vented euphonia",
"Golden-browed chlorophonia",
"Gray-crowned rosy-finch",
"Hawfinch",
"Hispaniolan crossbill",
"Hispaniolan euphonia",
"Hoary redpoll",
"Hooded grosbeak",
"House finch",
"Jamaican euphonia",
"Lawrence's goldfinch",
"Lesser Antillean euphonia",
"Lesser goldfinch",
"Lesser redpoll",
"Olive-backed euphonia",
"Orange-bellied euphonia",
"Oriental greenfinch",
"Pallas's rosefinch",
"Pine grosbeak",
"Pine siskin",
"Puerto Rican euphonia",
"Purple finch",
"Red crossbill",
"Red siskin",
"Scrub euphonia",
"Spot-crowned euphonia",
"Tawny-capped euphonia",
"Thick-billed euphonia",
"West Mexican euphonia",
"White-vented euphonia",
"White-winged crossbill",
"Yellow-bellied siskin",
"Yellow-collared chlorophonia",
"Yellow-crowned euphonia",
"Yellow-fronted canary",
"Yellow-throated euphonia",
"Chestnut-collared longspur",
"Lapland longspur",
"McKay's bunting",
"Smith's longspur",
"Snow bunting",
"Thick-billed longspur",
"Rosy thrush-tanager",
"Gray bunting",
"Little bunting",
"Pallas's bunting",
"Pine bunting",
"Reed bunting",
"Rustic bunting",
"Yellow-breasted buntingR",
"Yellow-browed bunting",
"Yellow-throated bunting",
"Abert's towhee",
"American tree sparrow",
"Ashy-throated chlorospingus",
"Bachman's sparrow",
"Baird's junco",
"Baird's sparrow",
"Bell's sparrow",
"Black-chested sparrow",
"Black-chinned sparrow",
"Black-headed brushfinch",
"Black-striped sparrow",
"Black-throated sparrow",
"Botteri's sparrow",
"Brewer's sparrow",
"Bridled sparrow",
"Cabanis's ground-sparrow",
"California towhee",
"Canyon towhee",
"Cassin's sparrow",
"Chestnut-capped brushfinch",
"Chipping sparrow",
"Cinnamon-tailed sparrow",
"Clay-colored sparrow",
"Collared towhee",
"Common chlorospingus",
"Costa Rican brushfinch",
"Dark-eyed junco",
"Eastern towhee",
"Field sparrow",
"Five-striped sparrow",
"Fox sparrow",
"Golden-crowned sparrow",
"Grasshopper sparrow",
"Green-backed sparrow",
"Green-striped brushfinch",
"Green-tailed towhee",
"Guadalupe junco",
"Harris's sparrow",
"Henslow's sparrow",
"Large-footed finch",
"Lark bunting",
"Lark sparrow",
"Le Conte's sparrow",
"Lincoln's sparrow",
"Nelson's sparrow",
"Oaxaca sparrow",
"Olive sparrow",
"Orange-billed sparrow",
"Pirre chlorospingus",
"Rufous-capped brushfinch",
"Rufous-collared sparrow",
"Rufous-crowned sparrow",
"Rufous-winged sparrow",
"Rusty sparrow",
"Rusty-crowned ground-sparrow",
"Sagebrush sparrow",
"Saltmarsh sparrow",
"Savannah sparrow",
"Seaside sparrow",
"Sierra Madre sparrow",
"Song sparrow",
"Sooty-capped chlorospingus",
"Sooty-faced finch",
"Spotted towhee",
"Striped sparrow",
"Stripe-headed sparrow",
"Swamp sparrow",
"Tacarcuna chlorospingus",
"Vesper sparrow",
"Volcano junco",
"White-crowned sparrow",
"White-eared ground-sparrow",
"White-faced ground-sparrow",
"White-naped brushfinch",
"White-throated sparrow",
"White-throated towhee",
"Worthen's sparrow",
"Yellow-eyed junco",
"Yellow-green brushfinch",
"Yellow-thighed brushfinch",
"Yellow-throated chlorospingus",
"Zapata sparrow",
"Eastern chat-tanager",
"Western chat-tanager",
"Black-crowned palm-tanager",
"Green-tailed warbler",
"Gray-crowned palm-tanager",
"White-winged warbler",
"Puerto Rican tanager",
"Hispaniolan spindalis",
"Jamaican spindalis",
"Puerto Rican spindalis",
"Western spindalis",
"Wrenthrush",
"Yellow-breasted chat",
"Altamira oriole",
"Audubon's oriole",
"Bahama oriole",
"Baltimore oriole",
"Bar-winged oriole",
"Black oropendola",
"Black-backed oriole",
"Black-cowled oriole",
"Black-vented oriole",
"Boat-tailed grackle",
"Bobolink",
"Brewer's blackbird",
"Bronzed cowbird",
"Brown-headed cowbird",
"Bullock's oriole",
"Carib grackle",
"Chestnut-headed oropendola",
"Chihuahuan meadowlark",
"Common grackle",
"Crested oropendola",
"Cuban blackbird",
"Cuban oriole",
"Eastern meadowlark",
"Giant cowbird",
"Greater Antillean grackle",
"Great-tailed grackle",
"Hispaniolan oriole",
"Hooded oriole",
"Jamaican blackbird",
"Jamaican oriole",
"Martinique oriole",
"Melodious blackbird",
"Montezuma oropendola",
"Montserrat oriole",
"Nicaraguan grackle",
"Orange oriole",
"Orange-crowned oriole",
"Orchard oriole",
"Puerto Rican oriole",
"Red-breasted meadowlark",
"Red-shouldered blackbird",
"Red-winged blackbird",
"Rusty blackbird",
"Scarlet-rumped cacique",
"Scott's oriole",
"Shiny cowbird",
"Slender-billed grackle",
"Spot-breasted oriole",
"St. Lucia oriole",
"Streak-backed oriole",
"Tawny-shouldered blackbird",
"Tricolored blackbird",
"Venezuelan troupial",
"Western meadowlark",
"Yellow-backed oriole",
"Yellow-billed cacique",
"Yellow-headed blackbird",
"Yellow-hooded blackbird",
"Yellow-rumped cacique",
"Yellow-shouldered blackbird",
"Yellow-tailed oriole",
"Yellow-winged cacique",
"Adelaide's warbler",
"Altamira yellowthroat",
"American redstart",
"Arrowhead warbler",
"Bachman's warbler",
"Bahama warbler",
"Bahama yellowthroat",
"Barbuda warbler",
"Bay-breasted warbler",
"Belding's yellowthroat",
"Black-and-white warbler",
"Blackburnian warbler",
"Black-cheeked warbler",
"Blackpoll warbler",
"Black-polled yellowthroat",
"Black-throated blue warbler",
"Black-throated gray warbler",
"Black-throated green warbler",
"Blue-winged warbler",
"Buff-rumped warbler",
"Canada warbler",
"Cape May warbler",
"Cerulean warbler",
"Chestnut-capped warbler",
"Chestnut-sided warbler",
"Colima warbler",
"Collared redstart",
"Common yellowthroat",
"Connecticut warbler",
"Costa Rican warbler",
"Crescent-chested warbler",
"Elfin-woods warbler",
"Fan-tailed warbler",
"Flame-throated warbler",
"Golden-browed warbler",
"Golden-cheeked warbler",
"Golden-crowned warbler",
"Golden-winged warbler",
"Grace's warbler",
"Gray-crowned yellowthroat",
"Hermit warbler",
"Hooded warbler",
"Hooded yellowthroat",
"Kentucky warbler",
"Kirtland's warbler",
"Louisiana waterthrush",
"Lucy's warbler",
"MacGillivray's warbler",
"Magnolia warbler",
"Mourning warbler",
"Nashville warbler",
"Northern parula",
"Northern waterthrush",
"Olive-capped warbler",
"Olive-crowned yellowthroat",
"Orange-crowned warbler",
"Ovenbird",
"Painted redstart",
"Palm warbler",
"Pine warbler",
"Pink-headed warbler",
"Pirre warbler",
"Plumbeous warbler",
"Prairie warbler",
"Prothonotary warbler",
"Red warbler",
"Red-faced warbler",
"Rufous-capped warbler",
"Semper's warbler",
"Slate-throated redstart",
"St. Lucia warbler",
"Swainson's warbler",
"Tacarcuna warbler",
"Tennessee warbler",
"Townsend's warbler",
"Tropical parula",
"Virginia's warbler",
"Vitelline warbler",
"Whistling warbler",
"Wilson's warbler",
"Worm-eating warbler",
"Yellow warbler",
"Yellow-rumped warbler",
"Yellow-throated warbler",
"Dusky-faced tanager",
"Black-cheeked ant-tanager",
"Black-faced grosbeak",
"Black-headed grosbeak",
"Black-thighed grosbeak",
"Blue bunting",
"Blue grosbeak",
"Blue seedeater",
"Blue-black grosbeak",
"Carmiol's tanager",
"Crimson-collared grosbeak",
"Dickcissel",
"Flame-colored tanager",
"Gray-throated chat",
"Hepatic tanager",
"Indigo bunting",
"Lazuli bunting",
"Lemon-spectacled tanager",
"Northern cardinal",
"Orange-breasted bunting",
"Painted bunting",
"Pyrrhuloxia",
"Red-breasted chat",
"Red-crowned ant-tanager",
"Red-headed tanager",
"Red-throated ant-tanager",
"Rose-bellied bunting",
"Rose-breasted grosbeak",
"Rose-throated tanager",
"Scarlet tanager",
"Summer tanager",
"Varied bunting",
"Western tanager",
"White-winged tanager",
"Yellow grosbeak",
"Yellow-green grosbeak",
"Azure-rumped tanager",
"Bananaquit",
"Barbados bullfinch",
"Bay-headed tanager",
"Black-and-yellow tanager",
"Black-faced grassquit",
"Black-headed saltator",
"Black-throated shrike-tanager",
"Blue dacnis",
"Blue-and-gold tanager",
"Blue-black grassquit",
"Blue-gray tanager",
"Buff-throated saltator",
"Cinnamon-bellied flowerpiercer",
"Cinnamon-bellied saltator",
"Cinnamon-rumped seedeater",
"Cocos finch",
"Crimson-backed tanager",
"Crimson-collared tanager",
"Cuban bullfinch",
"Cuban grassquit",
"Emerald tanager",
"Flame-rumped tanager",
"Golden-hooded tanager",
"Grassland yellow-finch",
"Greater Antillean bullfinch",
"Green honeycreeper",
"Green-naped tanager",
"Gray-and-gold tanager",
"Gray-headed tanager",
"Large-billed seed-finch",
"Lesser Antillean bullfinch",
"Lesser Antillean saltator",
"Lesser Antillean tanager",
"Lined seedeater",
"Morelet's seedeater",
"Nicaraguan seed-finch",
"Orangequit",
"Palm tanager",
"Peg-billed finch",
"Plain-colored tanager",
"Puerto Rican bullfinch",
"Purple honeycreeper",
"Red-legged honeycreeper",
"Ruddy-breasted seedeater",
"Rufous-winged tanager",
"Saffron finch",
"Scarlet-browed tanager",
"Scarlet-rumped tanager",
"Scarlet-thighed dacnis",
"Shining honeycreeper",
"Silver-throated tanager",
"Slate-colored grosbeak",
"Slate-colored seedeater",
"Slaty finch",
"Slaty flowerpiercer",
"Spangle-cheeked tanager",
"Speckled tanager",
"St. Kitts bullfinch",
"St. Lucia black finch",
"Streaked saltator",
"Sulphur-rumped tanager",
"Swallow tanager",
"Tawny-crested tanager",
"Thick-billed seed-finch",
"Variable seedeater",
"Viridian dacnis",
"Wedge-tailed grass-finch",
"White-eared conebill",
"White-lined tanager",
"White-shouldered tanager",
"White-throated shrike-tanager",
"Yellow-backed tanager",
"Yellow-bellied seedeater",
"Yellow-faced grassquit",
"Yellow-shouldered grassquit",
"Yellow-winged tanager",
"Spotted Whistling-Duck",
"Plumed Whistling-Duck",
"Fulvius Whistling-Duck",
"Wandering Whistling-Duck",
"Lesser Whistling-Duck",
"Bar-headed Goose",
"Emperor Goose",
"Snow Goose",
"Swan Goose",
"Greater White-fronted Goose",
"Lesser White-fronted Goose",
"Pink-Footed Goose",
"Cackling Goose",
"Canada Goose",
"Red-Breasted Goose",
"Black Swan",
"Trumpeter Swan",
"Knob-billed Buck",
"Radjah Shelduck",
"Ruddy Shelduck",
"Australian Shelduck",
"Common Shelduck",
"Crested Shelduck",
"Green Pygmy-Goose",
"Cotton Pygmy-Goose",
"Mandarin Duck",
"Salvadori's Teal",
"Baikal Teal",
"Blue-Winged Teal",
"Northern Shoveler",
"Falcated Duck",
"Eurasian Wigeon",
"American Wigeon",
"Pacific Black Duck",
"Philippine Duck",
"Indian Spot-Billed Duck",
"Eastern Spot-Billed Duck",
"American Black Duck",
"Northern Pintail",
"Green-Winged Teal",
"Andaman Teal",
"Sunda Teal",
"Gray Teal",
"Marbled Duck",
"Pink-Headed Duck",
"White-Winged Duck",
"Red-Crested Pochard",
"Common Pochard",
"Ring-Necked Duck",
"Ferruginous Duck",
"Baer's Pochard",
"Hardhead",
"Tufted Duck",
"Great Scaup",
"Lesser Scaup",
"Steller's Eider",
"Spectacled Eider",
"King Eider",
"Common Eider",
"Harlequin Duck",
"Surf Scoter",
"Velvet Scoter",
"White-Winged Scoter",
"Stejneger's Scoter",
"Common Scoter",
"Black Scoter",
"Long-Tailed Duck",
"Common Goldeneye",
"Barrow's Goldeneye",
"Hooded Merganser",
"Common Merganser",
"Red-Breasted Merganser",
"Scaly-Sided Merganser",
"Ruddy Duck",
"White-Headed Duck",
"Wattled Brushturkey",
"Waigeo Brushturkey",
"Red-Billed Brushturkey",
"Yellow-Legged Brushturkey",
"Red-Legged Brushturkey",
"Maleo",
"Moluccan Megapode",
"Nicobar Megapode",
"Philippine Megapode",
"Sula Megapode",
"Tanimbar Megapode",
"Dusky Megapode",
"Biak Megapode",
"New Guinea Megapode",
"Orange-Footed Megapode",
"Helmeted Guineafowl",
"Ferruginous Partridge",
"Crested Partridge",
"Black Partridge",
"Hill Partridge",
"Sichuan Partridge",
"Chestnut-Breasted Partridge",
"White-Necklaced Partridge",
"Rufous-Throated Partridge",
"Red-Billed Partridge",
"Chestnut-Headed Partridge",
"Hainan Partridge",
"Taiwan Partridge",
"White-Cheeked Partridge",
"Bar-Backed Partridge",
"Orange-Necked Partridge",
"Red-Breasted Partridge",
"Malayan Partridge",
"Roll's Partridge",
"Sumatran Partridge",
"Chestnut-Bellied Partridge",
"Gray-Breasted Partridge",
"Snow Partridge",
"Blood Pheasant",
"Western Tragopan",
"Satyr Tragopan",
"Blyth's Tragopan",
"Temminck's Tragopan",
"Cabot's Tragopan",
"Chestnut-Throated Monal-Partridge",
"Buff-Throated Monal-Partridge",
"Himalayan Monal",
"Sclater's Monal",
"Chinese Monal",
"Koklass Pheasant",
"Hazel Grouse",
"Chinese Grouse",
"Willow Ptarmigan",
"Rock Ptarmigan",
"Siberian Grouse",
"Western Capercaillie",
"Black-Billed Capercaillie",
"Black Grouse",
"Caucasian Grouse",
"Long-billed Partridge",
"Dulit Partridge",
"Tibetan Partridge",
"Daurian Partridge",
"Copper Pheasant",
"Reeves's Pheasant",
"Mikado Pheasant",
"Elliot's Pheasant",
"Mrs. Hume's Pheasant",
"Golden Pheasant",
"Lady Amherst's Pheasant",
"Ring-Necked Pheasant",
"Green Pheasant",
"Cheer Pheasant",
"Tibetan Eared-Pheasant",
"White Eared-Pheasant",
"Brown Eared-Pheasant",
"Blue Eared-Pheasant",
"Edwards's Pheasant",
"Swinhoe's Pheasant",
"Bulwer's Pheasant",
"Kalij Pheasant",
"Silver Pheasant",
"Malayan Crestless Fireback",
"Bornean Crestless Fireback",
"Siamese Fireback",
"Salvadori's Pheasant",
"Malayan Crested Fireback",
"Bornean Crested Fireback",
"Vietnamese Crested Argus",
"Malayan Crested Argus",
"Great Argus",
"Indian Peafowl",
"Green Peafowl",
"Scaly-breasted Partridge",
"Chestnut-necklaced Partridge",
"Sabah Partridge",
"Crimson-Headed Partridge",
"Red Spurfowl",
"Painted Spurfowl",
"Sri Lanka Spurfowl",
"Palawan Peacock-Pheasant",
"Bornean Peacock-Pheasant",
"Malayan Peacock-Pheasant",
"Germain's Peacock-Pheasant",
"Hainan Peacock-Pheasant",
"Gray Peacock-Pheasant",
"Mountain Peacock-Pheasant",
"Bronze-Tailed Peacock-Pheasant",
"Mountain Bamboo-Partridge",
"Chinese Bamboo-Partridge",
"Taiwan Bamboo-Partridge",
"Green Junglefowl",
"Red Junglefowl",
"Gray Junglefowl",
"Sri Lanka Junglefowl",
"Gray Francolin",
"Swamp Francolin",
"Chinese Francolin",
"Black Francolin",
"Painted Francolin",
"Tibetan Snowcock",
"Altai Snowcock",
"Caucasian Snowcock",
"Caspian Snowcock",
"Himalayan Snowcock",
"See-See Partridge",
"Sand Partridge",
"Brown Quail",
"Snow Mountain Quail",
"Blue-Breasted Quail",
"Common Quail",
"Japanese Quail",
"Harlequin Quail",
"Rain Quail",
"Arabian Partridge",
"Rock Partridge",
"Philby's Partridge",
"Przevalski's Partridge",
"Jungle Bush-Quail",
"Rock Bush-Quail",
"Painted Bush-Quail",
"Manipur Bush-Quail",
"Himalayan Quail",
"Rock Pigeon",
"Hill Pigeon",
"Snow Pigeon",
"Speckled Pigeon",
"Stock Dove",
"Yellow-Eyed Pigeon",
"Common Wood-Pigeon",
"Rameron Pigeon",
"Speckled Wood-Pigeon",
"Ashy Wood-Pigeon",
"Nilgiri Wood-Pigeon",
"Sri Lanka Wood-Pigeon",
"Pale-Capped Pigeon",
"Silvery Wood-Pigeon",
"Andaman Wood-Pigeon",
"Black Wood-Pigeon",
"Ryukyu Pigeon",
"Bonin Pigeon",
"Metallic Pigeon",
"Malagasy Turtle-Dove",
"European Turtle-Dove",
"Dusky Turtle-Dove",
"Oriental Turtle-Dove",
"Sunda Collared-Dove",
"Philippine Collared-Dove",
"Eurasian Collared-Dove",
"Burmese Collared-Dove",
"Red-Eyed Dove",
"Red Collared-Dove",
"Spotted Dove",
"Laughing Dove",
"Philippine Cuckoo-Dove",
"Ruddy Cuckoo-Dove",
"Black-Billed Cuckoo-Dove",
"Little Cuckoo-Dove",
"Great Cuckoo-Dove",
"Asian Emerald Dove",
"Pacific Emerald Dove",
"Stephan's Dove",
"New Guinea Bronzewing",
"Bronze Ground Dove",
"Zebra Dove",
"Peaceful Dove",
"Cinnamon Ground Dove",
"Mindoro Bleeding-Heart",
"Sulu Bleeding-Heart",
"Luzon Bleeding-Heart",
"Mindanao Bleeding-Heart",
"Tawitawi Brown-Dove",
"Pink-Necked Green-Pigeon",
"Wompoo Fruit-Dove",
"Jambu Fruit-Dove",
"Sula Fruit-Dove",
"Superb Fruit-Dove",
"Puna ibis",
"Black-headed ibis",
"Australian ibis",
"Straw-necked ibis",
"Red-naped ibis",
"White-shouldered ibis",
"Giant ibis",
"Northern bald ibis",
"Crested ibis",
"Royal spoonbill",
"African spoonbill",
"Black-faced spoonbill",
"Yellow-billed spoonbill",
"Wattled ibis",
"Tibetan sandgrouse",
"Pallas's sandgrouse",
"Pin-tailed sandgrouse",
"Spotted sandgrouse",
"Black-bellied sandgrouse",
"Crowned sandgrouse",
"Lichtenstein's sandgrouse",
"Painted sandgrouse",
"Four-banded sandgrouse",
"Great bustard",
"Arabian bustard",
"Great Indian bustard",
"Australian bustard",
"MacQueen's bustard",
"Houbara bustard",
"Bengal florican",
"Lesser florican",
"Little bustard",
"Sumatran ground-cuckoo",
"Bornean ground-cuckoo",
"Coral-billed ground-cuckoo",
"Biak coucal",
"Greater black coucal",
"Rufous coucal",
"Green-billed coucal",
"Black-faced coucal",
"Short-toed coucal",
"Black-hooded coucal",
"Bay coucal",
"White-browed coucal",
"Sunda coucal",
"Andaman coucal",
"Greater coucal",
"Goliath coucal",
"Philippine coucal",
"Lesser coucal",
"Lesser black coucal",
"Pheasant coucal",
"Pied coucal",
"Violaceous coucal",
"Senegal coucal",
"Raffles's malkoha",
"Sirkeer malkoha",
"Red-billed malkoha",
"Chestnut-breasted malkoha",
"Chestnut-bellied malkoha",
"Red-faced malkoha",
"Blue-faced malkoha",
"Black-bellied malkoha",
"Green-billed malkoha",
"Yellow-billed malkoha",
"Red-crested malkoha",
"Scale-feathered malkoha",
"Chestnut-winged cuckoo",
"Great spotted cuckoo",
"Pied cuckoo",
"Dwarf koel",
"Asian koel",
"Black-billed koel",
"Pacific koel",
"Long-tailed koel",
"Channel-billed cuckoo",
"Asian emerald cuckoo",
"Violet cuckoo",
"Dideric cuckoo",
"Klaas's cuckoo",
"Long-billed cuckoo",
"Horsfield's bronze-cuckoo",
"Black-eared cuckoo",
"Rufous-throated bronze-cuckoo",
"Shining bronze-cuckoo",
"White-eared bronze-cuckoo",
"Little bronze-cuckoo",
"Pallid cuckoo",
"White-crowned koel",
"Chestnut-breasted cuckoo",
"Fan-tailed cuckoo",
"Banded bay cuckoo",
"Plaintive cuckoo",
"Gray-bellied cuckoo",
"Moluccan cuckoo",
"Brush cuckoo",
"Fork-tailed drongo-cuckoo",
"Philippine drongo-cuckoo",
"Square-tailed drongo-cuckoo",
"Moluccan drongo-cuckoo",
"Moustached hawk-cuckoo",
"Large hawk cuckoo",
"Dark hawk-cuckoo",
"Common hawk-cuckoo",
"Northern hawk-cuckoo",
"Philippine hawk-cuckoo",
"Hodgson's hawk-cuckoo",
"Malaysian hawk-cuckoo",
"Lesser cuckoo",
"Sulawesi cuckoo",
"Indian cuckoo",
"Himalayan cuckoo",
"Sunda cuckoo",
"Common cuckoo",
"Oriental cuckoo",
"Marbled frogmouth",
"Papuan frogmouth",
"Tawny frogmouth",
"Large frogmouth",
"Dulit frogmouth",
"Philippine frogmouth",
"Gould's frogmouth",
"Sri Lanka frogmouth",
"Hodgson's frogmouth",
"Sumatran frogmouth",
"Bornean frogmouth",
"Javan frogmouth",
"Blyth's frogmouth",
"Palawan frogmouth",
"Sunda frogmouth",
"Solomons frogmouth",
"Spotted nightjar",
"Solomons nightjar",
"White-throated nightjar",
"Diabolical nightjar",
"Papuan nightjar",
"Archbold's nightjar",
"Malaysian eared-nightjar",
"Great eared-nightjar",
"Jungle nightjar",
"Eurasian nightjar",
"Egyptian nightjar",
"Nubian nightjar",
"Sykes's nightjar",
"Vaurie's nightjar",
"Large-tailed nightjar",
"Andaman nightjar",
"Mees's nightjar",
"Jerdon's nightjar",
"Philippine nightjar",
"Sulawesi nightjar",
"Indian nightjar",
"Plain nightjar",
"Savanna nightjar",
"Bonaparte's nightjar",
"Salvadori's nightjar",
"Red-necked nightjar",
"Montane nightjar",
"Golden nightjar",
"Feline owlet-nightjar",
"Starry owlet-nightjar",
"Wallace's owlet-nightjar",
"Mountain owlet-nightjar",
"Moluccan owlet-nightjar",
"Vogelkop owlet-nightjar",
"Barred owlet-nightjar",
"Australian owlet-nightjar",
"Philippine spinetailed swift",
"Papuan spinetailed swift",
"White-rumped needletail",
"Silver-rumped needletail",
"Sabine's spinetail",
"Silver-backed needletail",
"Brown-backed needletail",
"Purple needletail",
"Waterfall swift",
"Pygmy swiftlet",
"Bornean swiftlet",
"Cave swiftlet",
"Plume-toed swiftlet",
"Gray-rumped swiftlet",
"Ridgetop swiftlet",
"Tenggara swiftlet",
"Drab swiftlet",
"Glossy swiftlet",
"Satin swiftlet",
"Christmas Island swiftlet",
"Indian swiftlet",
"Sulawesi swiftlet",
"Halmahera swiftlet",
"Seram swiftlet",
"Philippine swiftlet",
"Mountain swiftlet",
"Himalayan swiftlet",
"Volcano swiftlet",
"Whitehead's swiftlet",
"Bare-legged swiftlet",
"Ameline swiftlet",
"Palawan swiftlet",
"Uniform swiftlet",
"Mossy-nest swiftlet",
"Black-nest swiftlet",
"White-nest swiftlet",
"German's swiftlet",
"Three-toed swiftlet",
"White-rumped swiftlet",
"Australian swiftlet",
"Mayr's swiftlet",
"Pallid swift",
"Pacific swift",
"Salim Ali's swift",
"Blyth's swift",
"Cook's swift",
"Dark-rumped swift",
"House swift",
"White-rumped swift",
"Plain swift",
"Forbes-Watson's swift",
"Asian palm-swift",
"African palm-swift",
"Crested treeswift",
"Gray-rumped treeswift",
"Whiskered treeswift",
"Moustached treeswift",
"Water rail",
"Brown-cheeked rail",
"Snoring rail",
"Slaty-breasted rail",
"Luzon rail",
"Lewin's rail",
"Blue-faced rail",
"Bare-eyed rail",
"Talaud rail",
"Calayan rail",
"Invisible rail",
"Chestnut rail",
"Okinawa rail",
"Buff-banded rail",
"Barred rail",
"New Britain rail",
"Woodford's rail",
"Weka",
"Lord Howe woodhen",
"Bar-winged rail",
"Eurasian moorhen",
"Dusky moorhen",
"Red-knobbed coot",
"Allen's gallinule",
"Black-backed swamphen",
"Australasian swamphen",
"Philippine swamphen",
"Gray-headed swamphen",
"African swamphen",
"New Guinea flightless rail",
"Watercock",
"Isabelline bush-hen",
"Plain bush-hen",
"White-breasted waterhen",
"Talaud bush-hen",
"Pale-vented bush-hen",
"Striped crake",
"White-browed crake",
"Chestnut forest-rail",
"White-striped forest-rail",
"Forbes's rail",
"Mayr's rail",
"Red-necked crake",
"Andaman crake",
"Red-legged crake",
"Slaty-legged crake",
"Ruddy-breasted crake",
"Band-bellied crake",
"Brown crake",
"Little crake",
"Baillon's crake",
"Black-tailed crake",
"Spotless crake",
"Swinhoe's rail",
"Black crake",
"Black-tailed nativehen",
"Tasmanian nativehen",
"Lesser moorhen",
"Giant wood-rail",
"Masked finfoot",
"Demoiselle crane",
"Siberian crane",
"Sarus crane",
"Brolga",
"White-naped crane",
"Black-necked crane",
"Red-crowned crane",
"Black crowned-crane",
"Black-faced sheathbill",
"Snowy sheathbill",
"Eurasian thick-knee",
"Indian thick-knee",
"Spotted thick-knee",
"Bush thick-knee",
"Senegal thick-knee",
"Peruvian thick-knee",
"Great thick-knee",
"Beach thick-knee",
"Egyptian plover",
"Pied stilt",
"Pied avocet",
"Red-necked avocet",
"Banded stilt",
"Pied oystercatcher",
"Sooty oystercatcher",
"South Island oystercatcher",
"Canarian oystercatcher",
"Blacksmith lapwing",
"Spur-winged plover",
"River lapwing",
"Yellow-wattled lapwing",
"Black-headed lapwing",
"Gray-headed lapwing",
"Red-wattled lapwing",
"Javan lapwing",
"Masked lapwing",
"Sociable lapwing",
"White-tailed lapwing",
"Banded lapwing",
"Black-winged lapwing",
"Crowned lapwing",
"Lesser sand-plover",
"Greater sand-plover",
"Caspian plover",
"Kittlitz's plover",
"Red-capped plover",
"Malaysian plover",
"Kentish plover",
"White-faced plover",
"Javan plover",
"Long-billed plover",
"Three-banded plover",
"Double-banded plover",
"White-fronted plover",
"Red-kneed dotterel",
"Black-fronted dotterel",
"Hooded plover",
"Inland dotterel, Peltohyas australis",
"Plains-wanderer",
"Greater painted-snipe",
"Comb-crested jacana",
"Pheasant-tailed jacana",
"Bronze-winged jacana",
"Asian dowitcher",
"Amami woodcock",
"Bukidnon woodcock",
"Javan woodcock",
"New Guinea woodcock",
"Sulawesi woodcock",
"Moluccan woodcock",
"Latham's snipe",
"Wood snipe",
"Great snipe",
"Swinhoe's snipe",
"Nordmann's greenshank",
"Small buttonquail",
"Red-backed buttonquail",
"Yellow-legged buttonquail",
"Spotted buttonquail",
"Barred buttonquail",
"Luzon buttonquail",
"Sumba buttonquail",
"Red-chested buttonquail",
"Black-breasted buttonquail",
"Chestnut-backed buttonquail",
"Buff-breasted buttonquail",
"Painted buttonquail",
"Little buttonquail",
"Crab-plover",
"Cream-colored courser",
"Indian courser",
"Temminck's courser",
"Jerdon's courser",
"Australian pratincole",
"Black-winged pratincole",
"Small pratincole",
"Bronze-winged courser",
"Brown skua",
"Spectacled guillemot",
"Japanese murrelet",
"Saunders's gull",
"Slender-billed gull",
"Silver gull",
"Brown-headed gull",
"Dolphin gull",
"Mediterranean gull",
"Relict gull",
"White-eyed gull",
"Sooty gull",
"Audouin's gull",
"Caspian gull",
"Armenian gull",
"Pacific gull",
"Lesser noddy",
"Grey noddy",
"Blue-gray noddy",
"Gray-backed tern",
"Little tern",
"Saunders's tern",
"Australian fairy tern",
"Black-naped tern",
"Black-bellied tern",
"River tern",
"White-cheeked tern",
"White-fronted tern",
"Antarctic tern",
"Great crested tern",
"Lesser crested tern",
"Chinese crested tern",
"African skimmer",
"Indian skimmer",
"Grey-headed albatross",
"Buller's albatross",
"Campbell albatross",
"Royal albatross",
"Sooty albatross",
"White-bellied storm-petrel",
"New Zealand storm-petrel",
"Grey-backed storm-petrel",
"Polynesian storm-petrel",
"Asian openbill",
"African openbill",
"Black stork",
"Abdim's stork",
"Asian woolly-necked stork",
"Storm's stork",
"Oriental stork",
"Black-necked stork",
"Lesser adjutant",
"Marabou stork",
"Greater adjutant",
"Milky stork",
"Yellow-billed stork",
"Painted stork",
"Saddle-billed stork",
"Abbott's booby",
"Oriental darter",
"Australasian darter",
"African darter",
"Little pied cormorant",
"Little cormorant",
"Pygmy cormorant",
"Long-tailed cormorant",
"Pallas's cormorant",
"Japanese cormorant",
"Socotra cormorant",
"Indian cormorant",
"Little black cormorant",
"Pied cormorant",
"Spotted shag",
"Black-faced cormorant",
"European shag",
"Kerguelen shag",
"Macquarie shag",
"Imperial shag",
"Australian pelican",
"Pink-backed pelican",
"Spot-billed pelican",
"Dalmatian pelican",
"Hamerkop",
"Australasian bittern",
"Yellow bittern",
"Black-backed bittern",
"Schrenck's bittern",
"Cinnamon bittern",
"Black bittern",
"Dwarf bittern",
"Forest bittern",
"Pacific heron",
"Black-headed heron",
"White-bellied heron",
"Great-billed heron",
"Goliath heron",
"White-faced heron",
"Pacific reef-heron",
"Pied heron",
"Black heron",
"Indian pond-heron",
"Javan pond-heron",
"Malagasy pond-heron",
"Nankeen night-heron",
"White-eared night-heron",
"Japanese night-heron",
"Malayan night-heron",
"White-backed night-heron",
"European roller",
"Abyssinian roller",
"Lilac-breasted roller",
"Rufous-crowned roller",
"Indian roller",
"Indochinese roller",
"Purple-winged roller",
"Broad-billed roller",
"Dollarbird",
"Azure roller",
"Sooty barbet",
"Brown barbet",
"Malabar barbet",
"Crimson-fronted barbet",
"Coppersmith barbet",
"Blue-eared barbet",
"Little barbet",
"Bornean barbet",
"Fire-tufted barbet",
"Great barbet",
"Red-vented barbet",
"Red-crowned barbet",
"Red-throated barbet",
"Black-banded barbet",
"Golden-naped barbet",
"Yellow-crowned barbet",
"Flame-fronted barbet",
"Green-eared barbet",
"Lineated barbet",
"Brown-headed barbet",
"White-cheeked barbet",
"Yellow-fronted barbet",
"Golden-throated barbet",
"Necklaced barbet",
"Mountain barbet",
"Brown-throated barbet",
"Golden-whiskered barbet",
"Moustached barbet",
"Taiwan barbet",
"Chinese barbet",
"Blue-throated barbet",
"Indochinese barbet",
"Black-browed barbet",
"Turquoise-throated barbet",
"Black-winged kite",
"Black-shouldered kite",
"Letter-winged kite",
"Scissor-tailed kite",
"Bearded vulture",
"Egyptian vulture",
"European honey-buzzard",
"Sulawesi honey-buzzard",
"Philippine honey-buzzard",
"Oriental honey-buzzard",
"Long-tailed honey-buzzard",
"Black honey-buzzard",
"Jerdon's baza",
"Pacific baza",
"Black baza",
"Red-headed vulture",
"Cinereous vulture",
"Lappet-faced vulture",
"White-rumped vulture",
"Indian vulture",
"Slender-billed vulture",
"Rüppell's griffon",
"Himalayan griffon",
"Eurasian griffon",
"White-backed vulture",
"Nicobar serpent-eagle",
"Sulawesi serpent-eagle",
"Mountain serpent-eagle",
"Crested serpent-eagle",
"Philippine serpent-eagle",
"Andaman serpent-eagle",
"Philippine eagle",
"Bateleur",
"Short-toed snake-eagle",
"Beaudouin's snake-eagle",
"Bat hawk",
"New Guinea eagle",
"Changeable hawk-eagle",
"Flores hawk-eagle",
"Mountain hawk-eagle",
"Legge's hawk-eagle",
"Blyth's hawk-eagle",
"Javan hawk-eagle",
"Sulawesi hawk-eagle",
"Philippine hawk-eagle",
"Pinsker's hawk-eagle",
"Wallace's hawk-eagle",
"Rufous-bellied eagle",
"Black eagle",
"Lesser spotted eagle",
"Indian spotted eagle",
"Greater spotted eagle",
"Pygmy eagle",
"Little eagle",
"Wahlberg's eagle",
"Tawny eagle",
"Steppe eagle",
"Imperial eagle",
"Gurney's eagle",
"Wedge-tailed eagle",
"Verreaux's eagle",
"Bonelli's eagle",
"Gabar goshawk",
"White-eyed buzzard",
"Rufous-winged buzzard",
"Gray-faced buzzard",
"Eurasian marsh-harrier",
"Eastern marsh-harrier",
"Papuan marsh-harrier",
"Spotted harrier",
"Hen harrier",
"Pallid harrier",
"Pied harrier",
"Montagu's harrier",
"Swamp harrier",
"Malagasy harrier",
"Crested goshawk",
"Sulawesi goshawk",
"Shikra",
"Nicobar sparrowhawk",
"Levant sparrowhawk",
"Spot-tailed goshawk",
"Variable goshawk",
"Brown goshawk",
"Black-mantled goshawk",
"Moluccan goshawk",
"Gray-headed goshawk",
"Japanese sparrowhawk",
"Small sparrowhawk",
"Besra",
"Rufous-necked sparrowhawk",
"Collared sparrowhawk",
"Vinous-breasted sparrowhawk",
"Northern goshawk",
"Meyer's goshawk",
"Gray goshawk",
"Black goshawk",
"Pied goshawk",
"Slaty-mantled goshawk",
"Imitator sparrowhawk",
"New Britain sparrowhawk",
"Fiji goshawk",
"Chestnut-shouldered goshawk",
"Doria's goshawk",
"Red kite",
"Whistling kite",
"Brahminy kite",
"Pallas's fish-eagle",
"White-bellied sea-eagle",
"Lesser fish-eagle",
"Gray-headed fish-eagle",
"Sanford's sea-eagle",
"Common buzzard",
"Himalayan buzzard",
"Eastern buzzard",
"Upland buzzard",
"Socotra buzzard",
"Cape Verde buzzard",
"Black-breasted kite",
"Square-tailed kite",
"Red goshawk",
"Hooded vulture",
"Dark chanting-goshawk",
"Eastern chanting-goshawk",
"Stripe-sided rhabdornis",
"Long-billed rhabdornis",
"Stripe-breasted rhabdornis",
"Visayan rhabdornis",
"Fiery-browed myna",
"Finch-billed myna",
"Metallic starling",
"Yellow-eyed starling",
"Tanimbar starling",
"Long-tailed starling",
"Singing starling",
"Asian glossy starling",
"Moluccan starling",
"Polynesian starling",
"Short-tailed starling",
"Sulawesi myna",
"Helmeted myna",
"Long-crested myna",
"Apo myna",
"Coleto",
"White-necked myna",
"Bare-eyed myna",
"Yellow-faced myna",
"Golden myna",
"Golden-crested myna",
"Sri Lanka myna",
"Common hill myna",
"Southern hill myna",
"Enggano myna",
"Nias myna",
"Spotless starling",
"Wattled starling",
"Rosy starling",
"Daurian starling",
"Chestnut-cheeked starling",
"Black-collared starling",
"Indian pied starling",
"Javan pied starling",
"Siamese pied starling",
"White-faced starling",
"Bali myna",
"White-shouldered starling",
"Brahminy starling",
"Chestnut-tailed starling",
"Malabar starling",
"Red-billed starling",
"White-cheeked starling",
"Bank myna",
"Burmese myna",
"Vinous-breasted myna",
"Black-winged myna",
"Jungle myna",
"Javan myna",
"Pale-bellied myna",
"Collared myna",
"Great myna",
"Crested myna",
"Tristram's starling",
"Somali starling",
"Socotra starling",
"Spot-winged starling",
"Purple starling",
"Superb starling",
"Splendid starling",
"Golden-breasted starling",
"Greater blue-eared starling",
"Cape starling",
"Violet-backed starling",
"White-browed tit-warbler",
"Crested tit-warbler",
"Long-tailed tit",
"Silver-throated tit",
"White-cheeked tit",
"Black-throated tit",
"White-throated tit",
"Black-browed tit",
"Sooty tit",
"Pygmy tit",
"Paradise-crow",
"Trumpet manucode",
"Curl-crested manucode",
"Crinkle-collared manucode",
"Jobi manucode",
"Glossy-mantled manucode",
"King-of-Saxony bird-of-paradise",
"Carola's parotia",
"Bronze parotia",
"Western parotia",
"Wahnes's parotia",
"Lawes's parotia",
"Twelve-wired bird-of-paradise",
"Black-billed sicklebill",
"Pale-billed sicklebill",
"Standardwing bird-of-paradise",
"Vogelkop lophorina",
"Greater lophorina",
"Magnificent riflebird",
"Growling riflebird",
"Black sicklebill",
"Brown sicklebill",
"Long-tailed paradigalla",
"Short-tailed paradigalla",
"Splendid astrapia",
"Arfak astrapia",
"Huon astrapia",
"Ribbon-tailed astrapia",
"Stephanie's astrapia",
"King bird-of-paradise",
"Wilson's bird-of-paradise",
"Magnificent bird-of-paradise",
"Blue bird-of-paradise",
"Emperor bird-of-paradise",
"Red bird-of-paradise",
"Goldie's bird-of-paradise",
"Lesser bird-of-paradise",
"Greater bird-of-paradise",
"Raggiana bird-of-paradise",
"Black magpie",
"Siberian jay",
"Sichuan jay",
"Eurasian jay",
"Black-headed jay",
"Lidth's jay",
"Azure-winged magpie",
"Sri Lanka blue-magpie",
"Taiwan blue-magpie",
"Yellow-billed blue-magpie",
"Red-billed blue-magpie",
"White-winged magpie",
"Common green-magpie",
"Indochinese green-magpie",
"Javan green-magpie",
"Bornean green-magpie",
"Rufous treepie",
"Gray treepie",
"Sumatran treepie",
"Bornean treepie",
"White-bellied treepie",
"Collared treepie",
"Andaman treepie",
"Racket-tailed treepie",
"Hooded treepie",
"Ratchet-tailed treepie",
"Black-rumped magpie",
"Oriental magpie",
"Eurasian magpie",
"Asir magpie",
"Mongolian ground-jay",
"Xinjiang ground-jay",
"Turkestan ground-jay",
"Iranian ground-jay",
"Eurasian nutcracker",
"Kashmir nutcracker",
"Red-billed chough",
"Yellow-billed chough",
"Daurian jackdaw",
"Banggai crow",
"Slender-billed crow",
"Violet crow",
"Piping crow",
"Flores crow",
"Long-billed crow",
"Brown-headed crow",
"Gray crow",
"Carrion crow",
"Large-billed crow",
"Torresian crow",
"Collared crow",
"Pied crow",
"Brown-necked raven",
"Fan-tailed raven",
"White-necked raven",
"Plush-crested jay",
"Fire-capped tit",
"Yellow-browed tit",
"Sultan tit",
"Coal tit",
"Rufous-naped tit",
"Rufous-vented tit",
"Yellow-bellied tit",
"Elegant tit",
"Palawan tit",
"Crested tit",
"Gray-crested tit",
"Chestnut-bellied tit",
"Iriomote tit",
"Varied tit",
"Owston's tit",
"White-fronted tit",
"White-browed tit",
"Sombre tit",
"Pere David's tit",
"Marsh tit",
"Black-bibbed tit",
"Willow tit",
"Sichuan tit",
"Caspian tit",
"Eurasian blue tit",
"Azure tit",
"African blue tit",
"Ground tit",
"Green-backed tit",
"Great tit",
"Cinereous tit",
"Japanese tit",
"White-naped tit",
"Taiwan yellow tit",
"Himalayan black-lored tit",
"Indian yellow tit",
"Yellow-cheeked tit",
"White-fronted scops-owl",
"Andaman scops-owl",
"Reddish scops-owl",
"Serendib scops-owl",
"Flores scops-owl",
"Mountain scops-owl",
"Rajah scops-owl",
"Javan scops-owl",
"Mentawai scops-owl",
"Indian scops-owl",
"Collared scops-owl",
"Giant scops-owl",
"Sunda scops-owl",
"Japanese scops-owl",
"Wallace's scops-owl",
"Palawan scops-owl",
"Philippine scops-owl",
"Everett's scops-owl",
"Negros scops-owl",
"Mindoro scops-owl",
"Moluccan scops-owl",
"Banggai scops-owl",
"Wetar scops-owl",
"Rinjani scops-owl",
"Mantanani scops-owl",
"Ryukyu scops-owl",
"Sulawesi scops-owl",
"Sangihe scops-owl",
"Siau scops-owl",
"Sula scops-owl",
"Biak scops-owl",
"Simeulue scops-owl",
"Enggano scops-owl",
"Nicobar scops-owl",
"Eurasian scops-owl",
"Cyprus scops-owl",
"Pallid scops-owl",
"Mindanao scops-owl",
"Luzon scops-owl",
"Arabian scops-owl",
"Socotra scops-owl",
"Eurasian eagle-owl",
"Rock eagle-owl",
"Pharaoh eagle-owl",
"Spot-bellied eagle-owl",
"Barred eagle-owl",
"Dusky eagle-owl",
"Philippine eagle-owl",
"Arabian eagle-owl",
"Grayish eagle-owl",
"Blakiston's fish-owl",
"Brown fish-owl",
"Tawny fish-owl",
"Buffy fish-owl",
"Eurasian pygmy-owl",
"Asian barred owlet",
"Javan owlet",
"Jungle owlet",
"Chestnut-backed owlet",
"Collared owlet",
"Sunda owlet",
"Spotted owlet",
"Little owl",
"Forest owlet",
"Spotted wood-owl",
"Mottled wood-owl",
"Brown wood-owl",
"Tawny owl",
"Himalayan owl",
"Desert owl",
"Ural owl",
"Omani owl",
"Marsh owl",
"Rufous ow",
"Barking owl",
"Sumba boobook",
"Andaman boobook",
"Alor boobook",
"Rote boobook",
"Timor boobook",
"Southern boobook",
"Morepork",
"Least boobook",
"Brown boobook",
"Hume's boobook",
"Chocolate boobook",
"Luzon boobook",
"Mindanao boobook",
"Mindoro boobook",
"Romblon boobook",
"Cebu boobook",
"Camiguin boobook",
"Sulu boobook",
"Ochre-bellied boobook",
"Togian boobook",
"Cinnabar boobook",
"Halmahera boobook",
"Tanimbar boobook",
"Seram boobook",
"Buru boobook",
"Christmas Island boobook",
"Papuan boobook",
"Speckled boobook",
"Manus boobook",
"Bismarck boobook",
"New Britain boobook",
"Solomons boobook",
"Powerful owl",
"Papuan owl",
"Fearful owl",
"Palm cockatoo",
"Little corella",
"Tanimbar corella",
"Philippine cockatoo",
"Yellow-crested cockatoo",
"Sulphur-crested cockatoo",
"Eleonora cockatoo",
"Salmon-crested cockatoo",
"White cockatoo",
"Southern cassowary",
"Dwarf cassowary",
"Northern cassowary",
"Philippine leafbird",
"Yellow-throated leafbird",
"Greater green leafbird",
"Lesser green leafbird",
"Blue-winged leafbird",
"Bornean leafbird",
"Jerdon's leafbird",
"Golden-fronted leafbird",
"Sumatran leafbird",
"Orange-bellied leafbird",
"Blue-masked leafbird", 
];

module.exports = {
	data: new SlashCommandBuilder()
		.setName('birdwatch')
		.setDescription('me olmec, you birdwatch'),
  
	async execute(interaction: any) {
	await interaction.deferReply();
	
	try {
	
		const isPokemon = Math.random() < SHINY_RATE;
		
		if (isPokemon) {
			const pokemonId = pokemonList[Math.floor(Math.random() * pokemonList.length)];
			const randomWeight = Math.floor(Math.random() * 1000) + 1;
			
			const pokeData = await fetchPokeAPI(`https://pokeapi.co/api/v2/pokemon/${pokemonId}`) as PokeAPIResponse;
			const imageUrl = pokeData.sprites.other['official-artwork'].front_shiny;
			const pokemonName = pokeData.name.charAt(0).toUpperCase() + pokeData.name.slice(1);
	        // Save to database
	        try {
	          await savePokemonCatch(interaction.user.id, {
	            pokemonId,
	            pokemonName,
	            weight: randomWeight,
	            imageUrl,
	            caughtAt: new Date()
	          });
	        } catch (dbError) {
	          console.error('Failed to save Pokémon to database:', dbError);
	          // Continue anyway - user still gets the Pokémon in chat
	        }
			if (!imageUrl) {
				return interaction.editReply(`Super rare mythical pull. You caught a shiny ${pokemonName}! It weighs ${randomWeight}kg <:pog:1416513137536008272>`);
			}
			
			return interaction.editReply({
				content: `Super rare mythical pull. You caught a shiny ${pokemonName}! It weighs ${randomWeight}kg <:pog:1416513137536008272>`,
				files: [imageUrl]
			});
		
		} else {
			const bird = birdList[Math.floor(Math.random() * birdList.length)];
			
			const searchData = await fetchWikipedia(
				`https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=${encodeURIComponent(bird)}&format=json`
			) as WikiSearchResult;
			
			if (!searchData.query?.search?.[0]) {
				return interaction.editReply(`You caught a ${bird}, but it got away!`);
			}
			
			const pageId = searchData.query.search[0].pageid;
			const pageData = await fetchWikipedia(
				`https://en.wikipedia.org/w/api.php?action=query&pageids=${pageId}&prop=pageimages&piprop=original|thumbnail&pithumbsize=800&format=json`
			) as WikiPageResult;
			
			const weightRange = getWeightRange(bird);
			const randomWeight = weightRange.max < 1 
			  ? (Math.random() * (weightRange.max - weightRange.min) + weightRange.min).toFixed(1) // small case
			  : Math.floor(Math.random() * (weightRange.max - weightRange.min + 1)) + weightRange.min;
			
			const page = pageData.query.pages[pageId];
			const imageUrl = page.thumbnail?.source || page.original?.source;
			
			if (!imageUrl) {
				return interaction.editReply(`You went birdwatching and saw a ${bird}, it weighs ${randomWeight}kg`);
			}

			const fileSize = await getFileSize(imageUrl);
			const MAX_SIZE = 25 * 1024 * 1024; //25mb
			
			if (fileSize > MAX_SIZE) {
				console.log(`img error`);
				return interaction.editReply({
				content: `You went birdwatching and saw a ${bird}, it weighs ${randomWeight}kg`,
				});
			}
			
			return interaction.editReply({
				content: `You went birdwatching and saw a ${bird}, it weighs ${randomWeight}kg`,
				files: [imageUrl]
			});
		}
		
	} catch (err) {
		console.error(err);
		return interaction.editReply("error bird img fetch");
	}
	}
};

// check /dig
function getFileSize(url: string): Promise<number> {
  return new Promise((resolve, reject) => {
    https.get(url, { method: 'HEAD' }, (res) => {
      const size = parseInt(res.headers['content-length'] || '0', 10);
      resolve(size);
    }).on('error', reject);
  });
}

function fetchWikipedia(url) {
  return new Promise((resolve, reject) => {
    const options = {
      headers: {
        'User-Agent': 'discord bot - animal command'
      }
    };
    https.get(url, options, (res) => {
      let data = '';
      res.on('data', (chunk) => data += chunk);
      res.on('end', () => {
        try {
          resolve(JSON.parse(data));
        } catch (e) {
          reject(e);
        }
      });
    }).on('error', reject);
  });
}

function fetchPokeAPI(url: string): Promise<unknown> {
  return new Promise((resolve, reject) => {
    const options = {
      headers: {
        'User-Agent': 'discord bot - animal command'
      }
    };
    https.get(url, options, (res) => {
      let data = '';
      res.on('data', (chunk) => data += chunk);
      res.on('end', () => {
        try {
          resolve(JSON.parse(data));
        } catch (e) {
          reject(e);
        }
      });
    }).on('error', reject);
  });
}

function getWeightRange(animalName: string): { min: number; max: number } {
  const name = animalName.toLowerCase();


  if (name.includes('eagle') || 
      name.includes('hawk') || 
      name.includes('vulture') || 
      name.includes('condor') || 
      name.includes('osprey')) {
    return { min: 0.5, max: 10 };
  }

  if (name.includes('albatross') || 
      name.includes('pelican') || 
      name.includes('swan') || 
      name.includes('goose') || 
      name.includes('crane') || 
      name.includes('stork')) {
    return { min: 2, max: 15 };
  }

  if (name.includes('duck') || 
      name.includes('teal') || 
      name.includes('merganser') || 
      name.includes('scoter') || 
      name.includes('eider')) {
    return { min: 0.3, max: 3 };
  }

  if (name.includes('hummingbird') || 
      name.includes('kinglet') || 
      name.includes('warbler') || 
      name.includes('chickadee') || 
      name.includes('wren') || 
      name.includes('gnatcatcher')) {
    return { min: 0.01, max: 0.05 };
  }

  if (name.includes('owl') || 
      name.includes('nightjar') || 
      name.includes('potoo') || 
      name.includes('frogmouth')) {
    return { min: 0.1, max: 4 };
  }

  if (name.includes('parrot') || 
      name.includes('macaw') || 
      name.includes('cockatoo') || 
      name.includes('parakeet') || 
      name.includes('lovebird')) {
    return { min: 0.03, max: 1.5 };
  }

  if (name.includes('woodpecker') || 
      name.includes('flicker') || 
      name.includes('sapsucker')) {
    return { min: 0.03, max: 0.3 };
  }

  if (name.includes('heron') || 
      name.includes('egret') || 
      name.includes('bittern') || 
      name.includes('ibis') || 
      name.includes('spoonbill')) {
    return { min: 0.1, max: 4 };
  }

  if (name.includes('gull') || 
      name.includes('tern') || 
      name.includes('skimmer') || 
      name.includes('jaeger') || 
      name.includes('skua')) {
    return { min: 0.1, max: 2 };
  }

  if (name.includes('penguin')) {
    return { min: 1, max: 50 };
  }

  if (name.includes('grouse') || 
      name.includes('ptarmigan') || 
      name.includes('pheasant') || 
      name.includes('partridge') || 
      name.includes('quail') || 
      name.includes('turkey')) {
    return { min: 0.1, max: 10 };
  }

  if (name.includes('dove') || 
      name.includes('pigeon')) {
    return { min: 0.1, max: 0.5 };
  }

  if (name.includes('swift') || 
      name.includes('swallow') || 
      name.includes('martin')) {
    return { min: 0.01, max: 0.06 };
  }

  if (name.includes('sandpiper') || 
      name.includes('plover') || 
      name.includes('snipe') || 
      name.includes('godwit') || 
      name.includes('curlew') || 
      name.includes('turnstone')) {
    return { min: 0.1, max: 1 };
  }

  if (name.includes('flycatcher') || 
      name.includes('kingbird') || 
      name.includes('phoebe') || 
      name.includes('pewee')) {
    return { min: 0.01, max: 0.05 };
  }

  if (name.includes('thrush') || 
      name.includes('robin') || 
      name.includes('bluebird') || 
      name.includes('solitaire')) {
    return { min: 0.1, max: 0.15 };
  }

  if (name.includes('sparrow') || 
      name.includes('bunting') || 
      name.includes('towhee') || 
      name.includes('junco')) {
    return { min: 0.01, max: 0.05 };
  }

  if (name.includes('finch') || 
      name.includes('siskin') || 
      name.includes('goldfinch') || 
      name.includes('rosefinch') || 
      name.includes('grosbeak')) {
    return { min: 0.1, max: 0.08 };
  }

  if (name.includes('tanager') || 
      name.includes('cardinal') || 
      name.includes('bunting')) {
    return { min: 0.015, max: 0.06 };
  }

  if (name.includes('jay') || 
      name.includes('crow') || 
      name.includes('raven') || 
      name.includes('magpie')) {
    return { min: 0.05, max: 1.5 };
  }

  if (name.includes('starling') || 
      name.includes('myna')) {
    return { min: 0.06, max: 0.15 };
  }

  if (name.includes('vireo') || 
      name.includes('greenlet')) {
    return { min: 0.1, max: 0.03 };
  }

  if (name.includes('kingfisher')) {
    return { min: 0.1, max: 0.3 };
  }

  if (name.includes('trogon') || 
      name.includes('quetzal')) {
    return { min: 0.04, max: 0.2 };
  }

  if (name.includes('booby') || 
      name.includes('gannet')) {
    return { min: 0.7, max: 3.5 };
  }

  if (name.includes('cormorant') || 
      name.includes('shag')) {
    return { min: 0.3, max: 5 };
  }

  if (name.includes('rail') || 
      name.includes('crake') || 
      name.includes('gallinule') || 
      name.includes('coot') || 
      name.includes('moorhen')) {
    return { min: 0.02, max: 2 };
  }

  if (name.includes('tinamou')) {
    return { min: 0.04, max: 2 };
  }

  if (name.includes('flamingo')) {
    return { min: 2, max: 4 };
  }

  if (name.includes('grebe')) {
    return { min: 0.1, max: 1.6 };
  }

  return { min: 1, max: 10 };
}
