const { SlashCommandBuilder } = require('discord.js');
const https = require('https');
import { savePokemonCatch } from '../services/pokemonService';
const TREASURE_RATE = 0.025;
const URL = 'https://raw.githubusercontent.com/tegberen/pokemonAutoChessBot/main/src/assets/';

interface WikiSearchResult {
  query?: {
    search?: Array<{ pageid: number }>;
  };
}

interface WikiPageResult {
  query: {
    pages: {
      [key: string]: {
        original?: {
          source: string;
        };
        thumbnail?: {
          source: string;
        };
      };
    };
  };
}

interface PokeAPIResponse {
  name: string;
  sprites: {
    other: {
      'official-artwork': {
        front_default: string | null;
		front_shiny: string | null;
      };
    };
  };
}


const dinoList = [
"Aachenosaurus",
"Aardonyx",
"Abdarainurus",
"Abditosaurus",
"Abelisaurus",
"Abrictosaurus",
"Abrosaurus",
"Abydosaurus",
"Acantholipan",
"Acanthopholis",
"Achelousaurus",
"Acheroraptor",
"Achillesaurus",
"Achillobator",
"Acristavus",
"Acrocanthosaurus",
"Acrotholus",
"Actiosaurus",
"Adamantisaurus",
"Adasaurus",
"Adelolophus",
"Adeopapposaurus",
"Adratiklit",
"Adynomosaurus",
"Aegyptosaurus",
"Aeolosaurus",
"Aepisaurus",
"Aepyornithomimus",
"Aerosteon",
"Aetonyx",
"Afromimus",
"Afrovenator",
"Agathaumas",
"Aggiosaurus",
"Agilisaurus",
"Agnosphitys",
"Agrosaurus",
"Agujaceratops",
"Agustinia",
"Ahshislepelta",
"Ahshislesaurus",
"Ahvaytum",
"Airakoraptor",
"Ajancingenia",
"Ajkaceratops",
"Ajnabia",
"Akainacephalus",
"Alamosaurus",
"Alamotyrannus",
"Alashansaurus",
"Alaskacephale",
"Albalophosaurus",
"Albertaceratops",
"Albertadromeus",
"Albertavenator",
"Albertonykus",
"Albertosaurus",
"Albinykus",
"Albisaurus",
"Alcovasaurus",
"Alectrosaurus",
"Aletopelta",
"Algoasaurus",
"Alioramus",
"Aliwalia",
"Allosaurus",
"Almas",
"Alnashetri",
"Alocodon",
"Alpkarakush",
"Altirhinus",
"Altispinax",
"Alvarezsaurus",
"Alwalkeria",
"Alxasaurus",
"Amanasaurus",
"Amanzia",
"Amargasaurus",
"Amargastegos",
"Amargatitanis",
"Amazonsaurus",
"Ambopteryx",
"Ammosaurus",
"Ampelognathus",
"Ampelosaurus",
"Amphicoelias",
"Amphicoelicaudia",
"Amphisaurus",
"Amtocephale",
"Amtosaurus",
"Amurosaurus",
"Amygdalodon",
"Anabisetia",
"Analong",
"Anasazisaurus",
"Anatosaurus",
"Anatotitan",
"Anchiceratops",
"Anchiornis",
"Anchisaurus",
"Andesaurus",
"Andhrasaurus",
"Angaturama",
"Angloposeidon",
"Angolatitan",
"Angulomastacator",
"Angustungui",
"Anhuilong",
"Aniksosaurus",
"Animantarx",
"Ankistrodon",
"Ankylosaurus",
"Anodontosaurus",
"Anomalipes",
"Anoplosaurus",
"Anserimimus",
"Antarctopelta",
"Antarctosaurus",
"Anteavis",
"Antetonitrus",
"Anthodon",
"Antrodemus",
"Anzu",
"Aoniraptor",
"Aorun",
"Apatodon",
"Apatoraptor",
"Apatosaurus",
"Appalachiosaurus",
"Aquilarhinus",
"Aquilops",
"Arackar",
"Aragosaurus",
"Aralosaurus",
"Aratasaurus",
"Araucanoraptor",
"Archaeoceratops",
"Archaeocursor",
"Archaeodontosaurus",
"Archaeopteryx",
"Archaeoraptor",
"Archaeornis",
"Archaeornithoides",
"Archaeornithomimus",
"Arcovenator",
"Arctosaurus",
"Arcusaurus",
"Ardetosaurus",
"Arenysaurus",
"Argentinosaurus",
"Argyrosaurus",
"Aristosaurus",
"Aristosuchus",
"Arizonasaurus",
"Arkansaurus",
"Arkharavia",
"Arrhinoceratops",
"Arrudatitan",
"Arstanosaurus",
"Asfaltovenator",
"Asiaceratops",
"Asiamericana",
"Asiatosaurus",
"Asiatyrannus",
"Asilisaurus",
"Astigmasaura",
"Astrodon",
"Astrodonius",
"Astrodontaurus",
"Astrophocaudia",
"Asylosaurus",
"Atacamatitan",
"Athenar",
"Atlantosaurus",
"Atlasaurus",
"Atlascopcosaurus",
"Atrociraptor",
"Atsinganosaurus",
"Aublysodon",
"Aucasaurus",
"Augustia",
"Augustynolophus",
"Auroraceratops",
"Aurornis",
"Australodocus",
"Australotitan",
"Australovenator",
"Austrocheirus",
"Austroposeidon",
"Austroraptor",
"Austrosaurus",
"Avaceratops",
"Avalonia",
"Avalonianus",
"Aviatyrannis",
"Avimimus",
"Avipes",
"Avisaurus",
"Azendohsaurus",
"Baalsaurus",
"Bactrosaurus",
"Bagaceratops",
"Bagaraatan",
"Bagualia",
"Bagualosaurus",
"Bahariasaurus",
"Bainoceratops",
"Baiyinosaurus",
"Bajadasaurus",
"Bakesaurus",
"Balaur",
"Balochisaurus",
"Bambiraptor",
"Banji",
"Bannykus",
"Baotianmansaurus",
"Barapasaurus",
"Barilium",
"Barosaurus",
"Barrosasaurus",
"Barsboldia",
"Baryonyx",
"Bashanosaurus",
"Bashunosaurus",
"Basutodon",
"Bathygnathus",
"Batyrosaurus",
"Baurutitan",
"Bayannurosaurus",
"Bayosaurus",
"Becklespinax",
"Beelemodon",
"Beibeilong",
"Beipiaognathus",
"Beipiaosaurus",
"Beishanlong",
"Bellusaurus",
"Belodon",
"Berberosaurus",
"Berthasaura",
"Betasuchus",
"Bicentenaria",
"Bienosaurus",
"Bihariosaurus",
"Bilbeyhallorum",
"Biscoveosaurus",
"Bissektipelta",
"Bistahieversor",
"Bisticeratops",
"Blasisaurus",
"Blikanasaurus",
"Bolong",
"Bonapartenykus",
"Bonapartesaurus",
"Bonatitan",
"Bonitasaura",
"Borealopelta",
"Borealosaurus",
"Boreonykus",
"Borogovia",
"Bothriospondylus",
"Brachiosaurus",
"Brachyceratops",
"Brachylophosaurus",
"Brachypodosaurus",
"Brachyrophus",
"Brachytaenius",
"Brachytrachelopan",
"Bradycneme",
"Brasileosaurus",
"Brasilotitan",
"Bravasaurus",
"Bravoceratops",
"Breviceratops",
"Brighstoneus",
"Brohisaurus",
"Brontomerus",
"Brontoraptor",
"Brontosaurus",
"Brontotholus",
"Bruhathkayosaurus",
"Bugenasaura",
"Buitreraptor",
"Burianosaurus",
"Buriolestes",
"Bustingorrytitan",
"Byranjaffia",
"Byronosaurus",
"Caenagnathasia",
"Caenagnathus",
"Caieiria",
"Caihong",
"Calamosaurus",
"Calamospondylus",
"Calamospondylus",
"Caletodraco",
"Callovosaurus",
"Calvarius",
"Camarasaurus",
"Camarillasaurus",
"Camelotia",
"Campananeyen",
"Camposaurus",
"Camptonotus",
"Camptosaurus",
"Campylodon",
"Campylodoniscus",
"Canardia",
"Capitalsaurus",
"Carcharodontosaurus",
"Cardiodon",
"Cariocecus",
"Carnotaurus",
"Caseosaurus",
"Cathartesaura",
"Cathetosaurus",
"Caudipteryx",
"Caudocoelus",
"Caulodon",
"Cedarosaurus",
"Cedarpelta",
"Cedrorestes",
"Centemodon",
"Centrosaurus",
"Cerasinops",
"Ceratonykus",
"Ceratops",
"Ceratosaurus",
"Ceratosuchops",
"Cetiosauriscus",
"Cetiosaurus",
"Chadititan",
"Chakisaurus",
"Changchunsaurus",
"Changdusaurus",
"Changmiania",
"Changyuraptor",
"Chaoyangsaurus",
"Charonosaurus",
"Chasmosaurus",
"Chassternbergia",
"Chebsaurus",
"Chenanisaurus",
"Cheneosaurus",
"Chialingosaurus",
"Chiayusaurus",
"Chienkosaurus",
"Chihuahuasaurus",
"Chilantaisaurus",
"Chilesaurus",
"Chindesaurus",
"Chingkankousaurus",
"Chinshakiangosaurus",
"Chirostenotes",
"Choconsaurus",
"Chondrosteosaurus",
"Choyrodon",
"Chromogisaurus",
"Chuandongocoelurus",
"Chuanjiesaurus",
"Chuanqilong",
"Chubutisaurus",
"Chucarosaurus",
"Chungkingosaurus",
"Chuxiongosaurus",
"Cienciargentina",
"Cinizasaurus",
"Cionodon",
"Citipati",
"Citipes",
"Cladeiodon",
"Claorhynchus",
"Claosaurus",
"Clarencea",
"Clasmodosaurus",
"Clepsysaurus",
"Coahuilaceratops",
"Coahuilasaurus",
"Coelophysis",
"Coelosaurus",
"Coeluroides",
"Coelurosauravus",
"Coelurus",
"Colepiocephale",
"Coloradia",
"Coloradisaurus",
"Colossosaurus",
"Comahuesaurus",
"Comanchesaurus",
"Compsognathus",
"Compsosuchus",
"Comptonatus",
"Concavenator",
"Conchoraptor",
"Condorraptor",
"Convolosaurus",
"Coronosaurus",
"Corythoraptor",
"Corythosaurus",
"Craspedodon",
"Crataeomus",
"Craterosaurus",
"Creosaurus",
"Crichtonpelta",
"Crichtonsaurus",
"Cristatusaurus",
"Crittendenceratops",
"Crosbysaurus",
"Cruxicheiros",
"Cryolophosaurus",
"Cryptodraco",
"Cryptoraptor",
"Cryptosaurus",
"Cryptovolans",
"Cumnoria",
"Daanosaurus",
"Dacentrurus",
"Dachongosaurus",
"Daemonosaurus",
"Dahalokely",
"Dakosaurus",
"Dakotadon",
"Dakotaraptor",
"Daliansaurus",
"Damalasaurus",
"Dandakosaurus",
"Danubiosaurus",
"Daptosaurus",
"Darwinsaurus",
"Dashanpusaurus",
"Daspletosaurus",
"Dasygnathoides",
"Dasygnathus",
"Datai",
"Datanglong",
"Datonglong",
"Datousaurus",
"Daurlon",
"Daurosaurus",
"Daxiatitan",
"Deinocheirus",
"Deinodon",
"Deinonychus",
"Delapparentia",
"Deltadromeus",
"Demandasaurus",
"Denversaurus",
"Deuterosaurus",
"Diabloceratops",
"Diamantinasaurus",
"Dianchungosaurus",
"Diceratops",
"Diceratus",
"Diclonius",
"Dicraeosaurus",
"Didanodon",
"Dilong",
"Dilophosaurus",
"Diluvicursor",
"Dimodosaurus",
"Dineobellator",
"Dinheirosaurus",
"Dinodocus",
"Dinosaurus",
"Dinotyrannus",
"Diodorus",
"Diplodocus",
"Diplotomodon",
"Diracodon",
"Diuqin",
"Dolichosuchus",
"Dollodon",
"Domeykosaurus",
"Dongbeititan",
"Dongyangopelta",
"Dongyangosaurus",
"Doratodon",
"Dornraptor",
"Doryphorosaurus",
"Draconyx",
"Dracopelta",
"Dracoraptor",
"Dracorex",
"Dracovenator",
"Dravidosaurus",
"Dreadnoughtus",
"Drinker",
"Dromaeosauroides",
"Dromaeosaurus",
"Dromiceiomimus",
"Dromicosaurus",
"Drusilasaura",
"Dryosaurus",
"Dryptosauroides",
"Dryptosaurus",
"Dubreuillosaurus",
"Duonychus",
"Duranteceratops",
"Duriatitan",
"Duriavenator",
"Dynamosaurus",
"Dynamoterror",
"Dyoplosaurus",
"Dysalotosaurus",
"Dysganus",
"Dyslocosaurus",
"Dystrophaeus",
"Dystylosaurus",
"Dzharacursor",
"Dzharaonyx",
"Dzharatitanis",
"Echinodon",
"Echizensaurus",
"Edmarka",
"Edmontonia",
"Edmontosaurus",
"Efraasia",
"Einiosaurus",
"Ekrixinatosaurus",
"Elachistosuchus",
"Elaltitan",
"Elaphrosaurus",
"Elemgasem",
"Elmisaurus",
"Elopteryx",
"Elosaurus",
"Elrhazosaurus",
"Elvisaurus",
"Emausaurus",
"Embasaurus",
"Emiliasaura",
"Enigmacursor",
"Enigmosaurus",
"Eoabelisaurus",
"Eobrontosaurus",
"Eocarcharia",
"Eoceratops",
"Eocursor",
"Eodromaeus",
"Eohadrosaurus",
"Eolambia",
"Eomamenchisaurus",
"Eoneophron",
"Eoplophysis",
"Eoraptor",
"Eosinopteryx",
"Eotrachodon",
"Eotriceratops",
"Eotyrannus",
"Eousdryosaurus",
"Epachthosaurus",
"Epanterias",
"Ephoenosaurus",
"Epicampodon",
"Epichirostenotes",
"Epidendrosaurus",
"Epidexipteryx",
"Equijubus",
"Erectopus",
"Erketu",
"Erliansaurus",
"Erlikosaurus",
"Erythrovenator",
"Eshanosaurus",
"Euacanthus",
"Eucamerotus",
"Eucentrosaurus",
"Eucercosaurus",
"Eucnemesaurus",
"Eucoelophysis",
"Eugongbusaurus",
"Euhelopus",
"Euoplocephalus",
"Eupodosaurus",
"Eureodon",
"Eurolimnornis",
"Euronychodon",
"Europasaurus",
"Europatitan",
"Europelta",
"Euskelosaurus",
"Eustreptospondylus",
"Fabrosaurus",
"Falcarius",
"Fendusaurus",
"Fenestrosaurus",
"Ferganasaurus",
"Ferganastegos",
"Ferganocephale",
"Ferrisaurus",
"Ferropectis",
"Fona",
"Foraminacephale",
"Fosterovenator",
"Fostoria",
"Francoposeidon",
"Frenguellisaurus",
"Fruitadens",
"Fujianvenator",
"Fukuiraptor",
"Fukuisaurus",
"Fukuititan",
"Fukuivenator",
"Fulengia",
"Fulgurotherium",
"Furcatoceratops",
"Fushanosaurus",
"Fusinasus",
"Fusuisaurus",
"Futabasaurus Futabasaurus",
"Futalognkosaurus",
"Fylax",
"Gadolosaurus",
"Galeamopus",
"Galesaurus",
"Galleonosaurus",
"Gallimimus",
"Galtonia",
"Galveosaurus",
"Galvesaurus",
"Gamatavus",
"Gandititan",
"Gannansaurus",
"Gansutitan",
"Ganzhousaurus",
"Gargoyleosaurus",
"Garrigatitan",
"Garudimimus",
"Garumbatitan",
"Gasosaurus",
"Gasparinisaura",
"Gastonia",
"Gavinosaurus",
"Geminiraptor",
"Genusaurus",
"Genyodectes",
"Geranosaurus",
"Gideonmantellia",
"Giganotosaurus",
"Gigantoraptor",
"Gigantosaurus",
"Gigantosaurus",
"Gigantoscelus",
"Gigantspinosaurus",
"Gilmoreosaurus",
"Ginnareemimus",
"Giraffatitan",
"Glacialisaurus",
"Glishades",
"Glyptodontopelta",
"Gnathovorax",
"Gobiceratops",
"Gobihadros",
"Gobiraptor",
"Gobisaurus",
"Gobititan",
"Gobivenator",
"Godzillasaurus",
"Gojirasaurus",
"Gondwanatitan",
"Gondwanax",
"Gongbusaurus",
"Gongpoquansaurus",
"Gongxianosaurus",
"Gonkoken",
"Gorgosaurus",
"Goyocephale",
"Graciliceratops",
"Graciliraptor",
"Gracilisuchus",
"Gravitholus",
"Gremlin",
"Gresslyosaurus",
"Griphornis",
"Griphosaurus",
"Gryphoceratops",
"Gryponyx",
"Gryposaurus",
"Gspsaurus",
"Guaibasaurus",
"Gualicho",
"Guanlong",
"Guemesia",
"Gwyneddosaurus",
"Gyposaurus",
"Hadrosauravus",
"Hadrosaurus",
"Haestasaurus",
"Hagryphus",
"Hallopus",
"Halszkaraptor",
"Halticosaurus",
"Hamititan",
"Hanssuesia",
"Hanwulosaurus",
"Haplocanthosaurus",
"Haplocanthus",
"Haplocheirus",
"Harenadraco",
"Harpymimus",
"Haya",
"Hecatasaurus",
"Heilongjiangosaurus",
"Heishansaurus",
"Helioceratops",
"Helopus",
"Heptasteornis",
"Herbstosaurus",
"Herrerasaurus",
"Hesperonychus",
"Hesperonyx",
"Hesperornithoides",
"Hesperosaurus",
"Heterodontosaurus",
"Heterosaurus",
"Hexing",
"Hexinlusaurus",
"Heyuannia",
"Hierosaurus",
"Hikanodon",
"Hippodraco",
"Hironosaurus",
"Hisanohamasaurus",
"Histriasaurus",
"Homalocephale",
"Honghesaurus",
"Hongshanosaurus",
"Hoplitosaurus",
"Hoplosaurus",
"Horshamosaurus",
"Hortalotarsus",
"Huabeisaurus",
"Huadanosaurus",
"Hualianceratops",
"Huallasaurus",
"Huanansaurus",
"Huanghetitan",
"Huangshanlong",
"Huashanosaurus",
"Huaxiagnathus",
"Huaxiaosaurus",
"Huaxiasaurus",
"Huaxiazhoulong",
"Huayangosaurus",
"Huayracursor",
"Hudiesaurus",
"Huehuecanauhtlus",
"Huinculsaurus",
"Hulsanpes",
"Hungarosaurus",
"Huxleysaurus",
"Hylaeosaurus",
"Hylosaurus",
"Hypacrosaurus",
"Hypnovenator",
"Hypselorhachis",
"Hypselosaurus",
"Hypselospinus",
"Hypsibema",
"Hypsilophodon",
"Hypsirhophus",
"Iani",
"Iberospinus",
"Ibirania",
"Ichabodcraniosaurus",
"Ichthyovenator",
"Igai",
"Ignavusaurus",
"Ignotosaurus",
"Iguanacolossus",
"Iguanodon",
"Iguanoides",
"Iguanosaurus",
"Ikqaumishan",
"Iliosuchus",
"Ilokelesia",
"Imperobator",
"Imrankhanhero",
"Imrankhanshaheen",
"Inawentu",
"Incisivosaurus",
"Indosaurus",
"Indosuchus",
"Ingenia",
"Ingentia",
"Inosaurus",
"Invictarx",
"Irisosaurus",
"Irritator",
"Isaberrysaura",
"Isanosaurus",
"Isasicursor",
"Ischioceratops",
"Ischisaurus",
"Ischyrosaurus",
"Isisaurus",
"Issi",
"Istiorachis",
"Itaguyra",
"Itapeuasaurus",
"Itemirus",
"Iuticosaurus",
"Iyuku",
"Jaculinykus",
"Jainosaurus",
"Jakapil",
"Jaklapallisaurus",
"Janenschia",
"Jaxartosaurus",
"Jeholosaurus",
"Jeholraptor",
"Jenghizkhan",
"Jensenosaurus",
"Jeyawati",
"Jianchangosaurus",
"Jiangjunmiaosaurus",
"Jiangjunosaurus",
"Jiangshanosaurus",
"Jiangxisaurus",
"Jiangxititan",
"Jianianhualong",
"Jinbeisaurus",
"Jinchuanloong",
"Jindipelta",
"Jinfengopteryx",
"Jingia",
"Jingiella",
"Jingshanosaurus",
"Jintasaurus",
"Jinyunpelta",
"Jinzhousaurus",
"Jiutaisaurus",
"Joaquinraptor",
"Jobaria",
"Jubbulpuria",
"Judiceratops",
"Julieraptor",
"Jurapteryx",
"Jurassosaurus",
"Juratyrant",
"Juravenator",
"Kaatedocus",
"Kagasaurus",
"Kaijiangosaurus",
"Kaijutitan",
"Kakuru",
"Kamuysaurus",
"Kangnasaurus",
"Kansaignathus",
"Karongasaurus",
"Katepensaurus",
"Katsuyamasaurus",
"Kayentavenator",
"Kazaklambia",
"Kelmayisaurus",
"Kelumapusaura",
"Kemkemia",
"Kentrosaurus",
"Kentrurosaurus",
"Kerberosaurus",
"Khaan",
"Khankhuuluu",
"Khetranisaurus",
"Kholumolumo",
"Khulsanurus",
"Kileskus",
"Kinnareemimus",
"Kitadanisaurus",
"Kittysaurus",
"Kiyacursor",
"Klamelisaurus",
"Kol",
"Koleken",
"Koparion",
"Koreaceratops",
"Koreanosaurus",
"Koreanosaurus",
"Koshisaurus",
"Kosmoceratops",
"Kotasaurus",
"Koutalisaurus",
"Kritosaurus",
"Kryptops",
"Krzyzanowskisaurus",
"Kukufeldia",
"Kulceratops",
"Kulindadromeus",
"Kulindapteryx",
"Kunbarrasaurus",
"Kundurosaurus",
"Kunmingosaurus",
"Kurupi",
"Kuszholia",
"Kwanasaurus",
"Kyacursor",
"Labocania",
"Labrosaurus",
"Laelaps",
"Laevisuchus",
"Lagerpeton",
"Lagosuchus",
"Laiyangosaurus",
"Lajasvenator",
"Lamaceratops",
"Lambeosaurus",
"Lametasaurus",
"Lamplughsaura",
"Lanasaurus",
"Lancangosaurus",
"Lancanjiangosaurus",
"Lanzhousaurus",
"Laosaurus",
"Lapampasaurus",
"Laplatasaurus",
"Lapparentosaurus",
"Laquintasaura",
"Latenivenatrix",
"Latirhinus",
"Lavocatisaurus",
"Leaellynasaura",
"Ledumahadi",
"Leinkupal",
"Leipsanosaurus",
"Lengosaurus",
"Leonerasaurus",
"Lepidocheirosaurus",
"Lepidus",
"Leptoceratops",
"Leptorhynchos",
"Leptospondylus",
"Leshansaurus",
"Lesothosaurus",
"Lessemsaurus",
"Levnesovia",
"Lewisuchus",
"Lexovisaurus",
"Leyesaurus",
"Liaoceratops",
"Liaoningosaurus",
"Liaoningotitan",
"Liaoningvenator",
"Liassaurus",
"Libycosaurus",
"Ligabueino",
"Ligabuesaurus",
"Likhoelesaurus",
"Liliensternus",
"Limaysaurus",
"Limnornis",
"Limnosaurus",
"Limusaurus",
"Lingwulong",
"Lingyuanosaurus",
"Linhenykus",
"Linheraptor",
"Linhevenator",
"Lirainosaurus",
"Lisboasaurus",
"Lishulong",
"Liubangosaurus",
"Llukalkan",
"Lohuecotitan",
"Lokiceratops",
"Loncosaurus",
"Longisquama",
"Longosaurus",
"Lopasaurus",
"Lophorhothon",
"Lophostropheus",
"Loricatosaurus",
"Loricosaurus",
"Losillasaurus",
"Lourinhanosaurus",
"Lourinhasaurus",
"Luanchuanraptor",
"Luanpingosaurus",
"Lucianosaurus",
"Lucianovenator",
"Lufengosaurus",
"Lukousaurus",
"Luoyanggia",
"Lurdusaurus",
"Lusitanosaurus",
"Lusotitan",
"Lusovenator",
"Lutungutali",
"Lycorhinus",
"Lythronax",
"Macelognathus",
"Machairasaurus",
"Machairoceratops",
"Macrocollum",
"Macrodontophion",
"Macrogryphosaurus",
"Macrophalangia",
"Macroscelosaurus",
"Macrurosaurus",
"Madsenius",
"Magnamanus",
"Magnapaulia",
"Magnirostris",
"Magnosaurus",
"Magulodon",
"Magyarosaurus",
"Mahakala",
"Mahuidacursor",
"Maiasaura",
"Maip",
"Majungasaurus",
"Majungatholus",
"Malarguesaurus",
"Malawisaurus",
"Maleevosaurus",
"Maleevus",
"Malefica",
"Maleriraptor",
"Maltaceratops",
"Mamenchisaurus",
"Mandschurosaurus",
"Manidens",
"Manospondylus",
"Mansourasaurus",
"Mantellisaurus",
"Mantellodon",
"Maojandino",
"Mapusaurus",
"Maraapunisaurus",
"Marasuchus",
"Marisaurus",
"Marmarospondylus",
"Marshosaurus",
"Martharaptor",
"Masiakasaurus",
"Massospondylus",
"Matheronodon",
"Maxakalisaurus",
"Mbiresaurus",
"Medusaceratops",
"Megacervixosaurus",
"Megadactylus",
"Megadontosaurus",
"Megalosaurus",
"Megapnosaurus",
"Megaraptor",
"Mei",
"Melanorosaurus",
"Mendozasaurus",
"Menefeeceratops",
"Menucocelsior",
"Meraxes",
"Mercuriceratops",
"Meroktenos",
"Merosaurus",
"Metriacanthosaurus",
"Mexidracon",
"Microcephale",
"Microceratops",
"Microceratus",
"Microcoelus",
"Microdontosaurus",
"Microhadrosaurus",
"Micropachycephalosaurus",
"Microraptor",
"Microvenator",
"Mierasaurus",
"Mifunesaurus",
"Migmanychion",
"Minimocursor",
"Minmi",
"Minotaurasaurus",
"Minqaria",
"Miragaia",
"Mirischia",
"Mnyamawamtuka",
"Moabosaurus",
"Mochlodon",
"Mohammadisaurus",
"Mojoceratops",
"Mongolosaurus",
"Mongolostegus",
"Monkonosaurus",
"Monoclonius",
"Monolophosaurus",
"Mononychus",
"Mononykus",
"Montanoceratops",
"Morelladon",
"Morinosaurus",
"Moros",
"Morosaurus",
"Morrosaurus",
"Mosaiceratops",
"Moshisaurus",
"Murusraptor",
"Musankwa",
"Mussaurus",
"Muttaburrasaurus",
"Muyelensaurus",
"Mymoorapelta",
"Naashoibitosaurus",
"Nambalia",
"Nankangia",
"Nanningosaurus",
"Nanosaurus",
"Nanotyrannus",
"Nanshiungosaurus",
"Nanuqsaurus",
"Nanyangosaurus",
"Napaisaurus",
"Narambuenatitan",
"Narindasaurus",
"Nasutoceratops",
"Natovenator",
"Natronasaurus",
"Navajoceratops",
"Nebulasaurus",
"Nectosaurus",
"Nedcolbertia",
"Nedoceratops",
"Neimongosaurus",
"Nemegtia",
"Nemegtomaia",
"Nemegtonykus",
"Nemegtosaurus",
"Neosaurus",
"Neosodon",
"Neovenator",
"Neuquenraptor",
"Neuquensaurus",
"Nevadadromeus",
"Newtonsaurus",
"Ngexisaurus",
"Ngwevu",
"Nhandumirim",
"Nicksaurus",
"Niebla",
"Ningyuansaurus",
"Ninjatitan",
"Niobrarasaurus",
"Nipponosaurus",
"Noasaurus",
"Nodocephalosaurus",
"Nodosaurus",
"Nomingia",
"Nopcsaspondylus",
"Normanniasaurus",
"Notatesseraeraptor",
"Nothronychus",
"Notoceratops",
"Notocolossus",
"Notohypsilophodon",
"Nqwebasaurus",
"Nteregosaurus",
"Nullotitan",
"Nurosaurus",
"Nuthetes",
"Nyasasaurus",
"Obelignathus",
"Oblitosaurus",
"Oceanotitan",
"Ohmdenosaurus",
"Ojoceratops",
"Ojoraptorsaurus",
"Oksoko",
"Oligosaurus",
"Olorotitan",
"Omeisaurus",
"Omosaurus",
"Ondogurvel",
"Onychosaurus",
"Oohkotokia",
"Opisthocoelicaudia",
"Oplosaurus",
"Orcomimus",
"Orinosaurus",
"Orkoraptor",
"Ornatops",
"Ornatotholus",
"Ornithodesmus",
"Ornithoides",
"Ornitholestes",
"Ornithomerus",
"Ornithomimoides",
"Ornithomimus",
"Ornithopsis",
"Ornithosuchus",
"Ornithotarsus",
"Orodromeus",
"Orosaurus",
"Orthogoniosaurus",
"Orthomerus",
"Oryctodromeus",
"Oshanosaurus",
"Osmakasaurus",
"Ostafrikasaurus",
"Ostromia",
"Othnielia",
"Othnielosaurus",
"Otogosaurus",
"Ouranosaurus",
"Overoraptor",
"Overosaurus",
"Oviraptor",
"Ovoraptor",
"Owenodon",
"Oxalaia",
"Ozraptor",
"Pachycephalosaurus",
"Pachyrhinosaurus",
"Pachysauriscus",
"Pachysaurops",
"Pachysaurus",
"Pachyspondylus",
"Pachysuchus",
"Padillasaurus",
"Pakisaurus",
"Palaeoctonus",
"Palaeocursornis",
"Palaeolimnornis",
"Palaeopteryx",
"Palaeosauriscus",
"Palaeosaurus",
"Palaeosaurus",
"Palaeoscincus",
"Paleosaurus",
"Paludititan",
"Paluxysaurus",
"Pampadromaeus",
"Pamparaptor",
"Panamericansaurus",
"Pandoravenator",
"Panguraptor",
"Panoplosaurus",
"Panphagia",
"Pantydraco",
"Papiliovenator",
"Paraiguanodon",
"Paralitherizinosaurus",
"Paralititan",
"Paranthodon",
"Pararhabdodon",
"Parasaurolophus",
"Paraxenisaurus",
"Pareiasaurus",
"Pareisactus",
"Parksosaurus",
"Paronychodon",
"Parrosaurus",
"Parvicursor",
"Patagonykus",
"Patagopelta",
"Patagosaurus",
"Patagotitan",
"Pawpawsaurus",
"Pectinodon",
"Pedopenna",
"Pegomastax",
"Peishansaurus",
"Pekinosaurus",
"Pelecanimimus",
"Pellegrinisaurus",
"Peloroplites",
"Pelorosaurus",
"Peltosaurus",
"Pendraig",
"Penelopognathus",
"Pentaceratops",
"Perijasaurus",
"Petrobrasaurus",
"Petrustitan",
"Phaedrolosaurus",
"Philovenator",
"Phuwiangosaurus",
"Phuwiangvenator",
"Phyllodon",
"Piatnitzkysaurus",
"Picrodon",
"Pilmatueia",
"Pinacosaurus",
"Pisanosaurus",
"Pitekunsaurus",
"Piveteausaurus",
"Planicoxa",
"Plateosauravus",
"Plateosaurus",
"Platyceratops",
"Platypelta",
"Platytholus",
"Plesiohadros",
"Pleurocoelus",
"Pleuropeltus",
"Pneumatoarthrus",
"Pneumatoraptor",
"Podischion",
"Podokesaurus",
"Poekilopleuron",
"Polacanthoides",
"Polacanthus",
"Polyodontosaurus",
"Polyonax",
"Ponerosteus",
"Poposaurus",
"Portellsaurus",
"Postosuchus",
"Powellvenator",
"Pradhania",
"Prenocephale",
"Prenoceratops",
"Priconodon",
"Priodontognathus",
"Proa",
"Probactrosaurus",
"Probrachylophosaurus",
"Proceratops",
"Proceratosaurus",
"Procerosaurus",
"Procerosaurus",
"Procheneosaurus",
"Procompsognathus",
"Prodeinodon",
"Proiguanodon",
"Propanoplosaurus",
"Proplanicoxa",
"Prosaurolophus",
"Protarchaeopteryx",
"Protathlitis",
"Protecovasaurus",
"Protiguanodon",
"Protoavis",
"Protoceratops",
"Protognathosaurus",
"Protognathus",
"Protohadros",
"Protorosaurus",
"Protorosaurus",
"Proyandusaurus",
"Pseudolagosuchus",
"Psittacosaurus",
"Pteropelyx",
"Pterospondylus",
"Puertasaurus",
"Pukyongosaurus",
"Pulanesaura",
"Pulaosaurus",
"Punatitan",
"Pycnonemosaurus",
"Pyroraptor",
"Qaikshaheen",
"Qantassaurus",
"Qianjiangsaurus",
"Qianlong",
"Qianzhousaurus",
"Qiaowanlong",
"Qijianglong",
"Qingxiusaurus",
"Qinlingosaurus",
"Qiupalong",
"Qiupanykus",
"Quaesitosaurus",
"Quetecsaurus",
"Quilmesaurus",
"Qunkasaura",
"Rachitrema",
"Rahiolisaurus",
"Rahona",
"Rahonavis",
"Rajasaurus",
"Rapator",
"Rapetosaurus",
"Raptorex",
"Ratchasimasaurus",
"Rativates",
"Rayososaurus",
"Razanandrongobe",
"Rebbachisaurus",
"Regaliceratops",
"Regnosaurus",
"Revueltosaurus",
"Rhabdodon",
"Rhadinosaurus",
"Rhinorex",
"Rhodanosaurus",
"Rhoetosaurus",
"Rhomaleopakhus",
"Rhopalodon",
"Riabininohadros",
"Richardoestesia",
"Rileya",
"Rileyasuchus",
"Rinchenia",
"Rinconsaurus",
"Rioarribasaurus",
"Riodevasaurus",
"Riojasaurus",
"Riojasuchus",
"Riojavenatrix",
"Riparovenator",
"Rocasaurus",
"Roccosaurus",
"Ronaldoraptor",
"Rubeosaurus",
"Ruehleia",
"Rugocaudia",
"Rugops",
"Ruixinia",
"[124]",
"Rukwatitan",
"Rutellum",
"Ruyangosaurus",
"Sabinosaurus",
"Sacisaurus",
"Sahaliyania",
"Saichania",
"Saldamosaurus",
"Saltasaurus",
"Saltillomimus",
"Saltopus",
"Saltriosaurus",
"Saltriovenator",
"Sanchusaurus",
"Sangonghesaurus",
"Sanjuansaurus",
"Sanpasaurus",
"Santanaraptor",
"Sanxiasaurus",
"Sarahsaurus",
"Saraikimasoom",
"Saraikisaurus",
"Sarcolestes",
"Sarcosaurus",
"Sarmientosaurus",
"Sasayamagnomus",
"Saturnalia",
"Sauraechinodon",
"Sauraechmodon",
"Saurechinodon",
"Saurolophus",
"Sauroniops",
"Sauropelta",
"Saurophaganax",
"Saurophagus",
"Sauroplites",
"Sauropodus",
"Sauroposeidon",
"Saurornithoides",
"Saurornitholestes",
"Savannasaurus",
"Scansoriopteryx",
"Scaphonyx",
"Scelidosaurus",
"Schleitheimia",
"Scipionyx",
"Sciurumimus",
"Scleromochlus",
"Scolosaurus",
"Scutellosaurus",
"Secernosaurus",
"Sefapanosaurus",
"Segisaurus",
"Segnosaurus",
"Seismosaurus",
"Seitaad",
"Sektensaurus",
"Sellacoxa",
"Sellosaurus",
"Serendipaceratops",
"Serikornis",
"Shamosaurus",
"Shanag",
"Shanshanosaurus",
"Shantungosaurus",
"Shanxia",
"Shanyangosaurus",
"Shaochilong",
"Shenzhousaurus",
"Shidaisaurus",
"Shingopana",
"Shishugounykus",
"Shixinggia",
"Shri",
"Shuangbaisaurus",
"Shuangmiaosaurus",
"Shunosaurus",
"Shuvosaurus",
"Shuvuuia",
"Siamodon",
"Siamodracon",
"Siamosaurus",
"Siamotyrannus",
"Siamraptor",
"Siats",
"Sibirosaurus",
"Sibirotitan",
"Sidersaura",
""Sidormimus",
"Sierraceratops",
"Sigilmassasaurus",
"Silesaurus",
"Siluosaurus",
"Silutitan",
"Silvisaurus",
"Similicaudipteryx",
"Sinankylosaurus",
"Sinocalliopteryx",
"Sinocephale",
"Sinoceratops",
"Sinocoelurus",
"Sinopelta",
"Sinopeltosaurus",
"Sinopliosaurus",
"Sinornithoides",
"Sinornithomimus",
"Sinornithosaurus",
"Sinosauropteryx",
"Sinosaurus",
"Sinotyrannus",
"Sinovenator",
"Sinraptor",
"Sinusonasus",
"Sirindhorna",
"Skaladromeus",
"Skorpiovenator",
"Smilodon",
"Smitanosaurus",
"Smok",
"Sonidosaurus",
"Sonorasaurus",
"Soriatitan",
"Soumyasaurus",
"Spectrovenator",
"Sphaerotholus",
"Sphenosaurus",
"Sphenospondylus",
"Spiclypeus",
"Spicomellus",
"Spinophorosaurus",
"Spinops",
"Spinosaurus",
"Spinostropheus",
"Spinosuchus",
"Spondylosoma",
"Squalodon",
"Staurikosaurus",
"Stegoceras",
"Stegopelta",
"Stegosaurides",
"Stegosaurus",
"Stegotitanus",
"Stegouros",
"Stellasaurus",
"Stenonychosaurus",
"Stenopelix",
"Stenotholus",
"Stephanosaurus",
"Stereocephalus",
"Sterrholophus",
"Stokesosaurus",
"Stormbergia",
"Strenusaurus",
"Streptospondylus",
"Struthiomimus",
"Struthiosaurus",
"Stygimoloch",
"Stygivenator",
"Styracosaurus",
"Succinodon",
"Suchomimus",
"Suchoprion",
"Suchosaurus",
"Suciasaurus",
"Sugiyamasaurus",
"Sulaimanisaurus",
"Supersaurus",
"Suskityrannus",
"Suuwassea",
"Suzhousaurus",
"Symphyrophus",
"Syngonosaurus",
"Syntarsus",
"Syrmosaurus",
"Szechuanosaurus",
"Tachiraptor",
"Talarurus",
"Talenkauen",
"Taleta",
"Talos",
"Tamarro",
"Tambatitanis",
"Tameryraptor",
"Tangvayosaurus",
"Tanius",
"Tanycolagreus",
"Tanystropheus",
"Tanystrosuchus",
"Taohelong",
"Tapinocephalus",
"Tapuiasaurus",
"Tarascosaurus",
"Tarbosaurus",
"Tarchia",
"Tastavinsaurus",
"Tatankacephalus",
"Tatankaceratops",
"Tataouinea",
"Tatisaurus",
"Taurovenator",
"Taveirosaurus",
"Tawa",
"Tawasaurus",
"Tazoudasaurus",
"Technosaurus",
"Tecovasaurus",
"Tehuelchesaurus",
"Teihivenator",
"Teinurosaurus",
"Teleocrater",
"Telmatosaurus",
"Tenantosaurus",
"Tenchisaurus",
"Tendaguria",
"Tengrisaurus",
"Tenontosaurus",
"Teratophoneus",
"Teratosaurus",
"Termatosaurus",
"Terminocavus",
"Tethyshadros",
"Tetragonosaurus",
"Texacephale",
"Texasetes",
"Teyuwasu",
"Thanatotheristes",
"Thanos",
"Tharosaurus",
"Thecocoelurus",
"Thecodontosaurus",
"Thecospondylus",
"Theiophytalia",
"Therizinosaurus",
"Therosaurus",
"Thescelosaurus",
"Thespesius",
"Thotobolosaurus",
"Thyreosaurus",
"Tiamat",
"Tianchiasaurus",
"Tianchisaurus",
"Tianchungosaurus",
"Tianyulong",
"Tianyuraptor",
"Tianzhenosaurus",
"Tichosteus",
"Tienshanosaurus",
"Tietasaura",
"[136]",
"Timimus",
"Timurlengia",
"Titanoceratops",
"Titanomachya",
"Titanosaurus",
"Titanosaurus",
"Tlatolophus",
"Tochisaurus",
"Tomodon",
"Tonganosaurus",
"Tongnanlong",
"Tongtianlong",
"Tonouchisaurus",
"Torilion",
"Tornieria",
"Torosaurus",
"Torvosaurus",
"Tototlmimus",
"Trachelosaurus",
"Trachodon",
"Tralkasaurus",
"Transylvanosaurus",
"Tratayenia",
"Traukutitan",
"Trialestes",
"Triassolestes",
"Tribelesodon",
"Triceratops",
"Trierarchuncus",
"Trigonosaurus",
"Trimucrodon",
"Trinisaura",
"Triunfosaurus",
"Troodon",
"Tsaagan",
"Tsagantegia",
"Tsintaosaurus",
"Tuebingosaurus",
"Tugulusaurus",
"Tuojiangosaurus",
"Turanoceratops",
"Turiasaurus",
"Tylocephale",
"Tylosteus",
"Tyrannomimus",
"Tyrannosaurus",
"Tyrannotitan",
"Uberabatitan",
"Ubirajara",
"Udanoceratops",
"Udelartitan",
"Ugrosaurus",
"Ugrunaaluk",
"Uintasaurus",
"Ultrasauros",
"Ultrasaurus Supersaurus",
"Ultrasaurus",
"Ulughbegsaurus",
"[143]",
"Umarsaurus",
"Unaysaurus",
"Unenlagia",
"Unescoceratops",
"Unicerosaurus",
"Unquillosaurus",
"Urbacodon",
"Uriash",
"Utahceratops",
"Utahraptor",
"Uteodon",
"Utetitan",
"Vagaceratops",
"Vahiny",
"Valdoraptor",
"Valdosaurus",
"Vallibonavenatrix",
"Variraptor",
"Vayuraptor",
"Vectaerovenator",
"Vectensia",
"Vectidromeus",
"Vectipelta",
"Vectiraptor",
"Vectisaurus",
"Vectispinus",
"Velafrons",
"Velocipes",
"Velociraptor",
"Velocisaurus",
"Venaticosuchus",
"Venenosaurus",
"Vespersaurus",
"Veterupristisaurus",
"Viavenator",
"Vitakridrinda",
"Vitakrisaurus",
"Vitosaura",
"Volgatitan",
"Volkheimeria",
"Vouivria",
"Vulcanodon",
"Wadhurstia",
"Wakinosaurus",
"Walgettosuchus",
"Walkeria",
"Walkersaurus",
"Wamweracaudia",
"Wannanosaurus",
"Weewarrasaurus",
"Wellnhoferia",
"Wendiceratops",
"Wiehenvenator",
"Willinakaqe",
"Wintonotitan",
"Wudingloong",
"Wuerhosaurus",
"Wulagasaurus",
"Wulatelong",
"Wulatesaurus",
"Wulong",
"Wyleyia",
"Wyomingraptor",
"Xenoceratops",
"Xenoposeidon",
"Xenotarsosaurus",
"Xianshanosaurus",
"Xiaosaurus",
"Xiaotingia",
"Xinghesaurus",
"Xingtianosaurus",
"Xingxiulong",
"Xinjiangovenator",
"Xinjiangtitan",
"Xiongguanlong",
"Xixianykus",
"Xixiasaurus",
"Xixiposaurus",
"Xiyunykus",
"Xuanhanosaurus",
"Xuanhuaceratops",
"Xuanhuasaurus",
"Xunmenglong",
"Xuwulong",
"Yaleosaurus",
"Yamaceratops",
"Yamanasaurus",
"Yamatosaurus",
"Yanbeilong",
"Yandusaurus",
"Yangchuanosaurus",
"Yaverlandia",
"Yehuecauhceratops",
"Yezosaurus Taniwhasaurus",
"Yi",
"Yibinosaurus",
"Yimenosaurus",
"Yingshanosaurus",
"Yinlong",
"Yixianosaurus",
"Yizhousaurus",
"Yongjinglong",
"Ypupiara",
"Yuanmouraptor",
"Yuanmousaurus",
"Yuanyanglong",
"Yueosaurus",
"Yulong",
"Yunganglong",
"Yunmenglong",
"Yunnanosaurus",
"Yunxianosaurus",
"Yunyangosaurus",
"Yurgovuchia",
"Yutyrannus",
"Yuxisaurus",
"Yuzhoulong",
"Zalmoxes",
"Zanabazar",
"Zanclodon",
"Zapalasaurus",
"Zapsalis",
"Zaraapelta",
"Zatomus",
"Zavacephale",
"Zby",
"Zephyrosaurus",
"Zhanghenglong",
"Zhejiangosaurus",
"Zhenyuanlong",
"Zhongjianosaurus",
"Zhongornis",
"Zhongyuansaurus",
"Zhuchengceratops",
"Zhuchengosaurus",
"Zhuchengtitan",
"Zhuchengtyrannus",
"Ziapelta",
"Zigongosaurus",
"Zizhongosaurus",
"Zuniceratops",
"Zunityrannus",
"Zuolong",
"Zuoyunlong",
"Zupaysaurus",
"Zuul",
];
const pokemonFossilIds = [
    138, //Amonitas, "Amonitas"
    139, //Amoroso, "Amoroso"
    140, //Kabuto, "Kabuto"
    141, //Kabutops, "Kabutops"
    142, //Aerodactyl Mega, "Aerodactyl Mega"
    142, //Aerodactyl, "Aerodactyl"
    345, //Liliep, "Liliep"
    346, //Wielie, "Wielie"
    347, //Anorith, "Anorith"
    348, //Armaldo, "Armaldo"
    408, //Koknodon, "Koknodon"
    409, //Rameidon, "Rameidon"
    410, //Schilterus, "Schilterus"
    411, //Bollterus, "Bollterus"
    564, //Galapaflos, "Galapaflos"
    565, //Karippas, "Karippas"
    566, //Flapteryx, "Flapteryx"
    567, //Aeropteryx, "Aeropteryx"
    696, //Balgoras, "Balgoras"
    697, //Monargoras, "Monargoras"
    698, //Amarino, "Amarino"
    699, //Amagarga, "Amagarga"
    880, //Lectragon, "Lectragon"
    881, //Lecryodon, "Lecryodon"
    882, //Pescragon, "Pescragon"
    883,  //Pescryodon, "Pescryodon"

	493 //arceus
];

const treasureList = [
  { name: "an Ancient Aztec Codex", imageUrl: `${URL}aztec_code.webp` },
  { name: "a Box of Scooby-Snacks", imageUrl: `${URL}scooby_snack.webp` },
  { name: "a Pair of Lightning McQueen Crocs", imageUrl: `${URL}mcqueen_shoes.webp` },
  { name: "a Wimpod Sitting Cutie", imageUrl: `${URL}wimpod.webp` },
  { name: "Tort's Favorite Blanket Hoodie", imageUrl: `${URL}torthood.webp` },
  { name: "a Winning Scratch-Off Ticket", imageUrl: `${URL}lottery.webp` },
  { name: "a 2,000 Litre Barrel of Toxic Waste", imageUrl: `${URL}toxic_waste.webp` },
  { name: "a Giant Diamond", imageUrl: `${URL}diamond.webp` },
  { name: "an Exp. Share", imageUrl: `${URL}exp_share.webp` },
  { name: "a White Castle Crave Case", imageUrl: `${URL}crave_case.webp` },
  { name: "a Big Golden Nugget", imageUrl: `${URL}goldnugget.webp` },
  { name: "a PSA 10 Charizard Card", imageUrl: `${URL}sandshrew_card.webp` },
  { name: "a Cool Rat Wearing a Tophat", imageUrl: `${URL}mouse.webp` },
  { name: "a Well-Used Toothbrush", imageUrl: `${URL}toothbrush.webp` },
  { name: "a Half-Eaten Bag of Gummy Worms", imageUrl: `${URL}gummies.webp` },
  { name: "a Bag of Garbage", imageUrl: `${URL}trashbag.webp` },
  { name: "Sandshrew's Pokemon Card Collection", imageUrl: `${URL}sandshrew_card.webp` },
  { name: "a Giant Stone Olmec Head", imageUrl: `${URL}olmec.webp` },
  { name: "a Chinese Statue Made of Bronze", imageUrl: `${URL}chinese_statue.webp` },
  { name: "Kanga-Can", imageUrl: `${URL}kanga_can.webp` },
  { name: "a Nintendo Wii and Copy of Mario Kart", imageUrl: `${URL}wii.webp` },
  { name: "the Holy Grail", imageUrl: `${URL}holy_grail.webp` },
  { name: "a Bacon, Egg, and Cheese Breakfast Sandwich", imageUrl: `${URL}bacon_cheese.webp` },
  { name: "a Greek Statue Made of Marble", imageUrl: `${URL}greek_statue.webp` },
  { name: "a Really Cool Looking Stick", imageUrl: `${URL}cheerios.webp` },
  { name: "a Box of Honey Nut Cheerios", imageUrl: `${URL}cheerios.webp` },
  { name: "a Wheel of Curry's Favourite Cheese", imageUrl: `${URL}cheese.webp` },
  { name: "a Copy of Zoboomafoo on VHS", imageUrl: `${URL}zoboomafoo.webp` },
  { name: "a Jar Filled With Strawberry Jam", imageUrl: `${URL}jam.webp` },
  { name: "an Unopened Can of Zero-Sugar Redbull", imageUrl: `${URL}redbull.webp` },
  { name: "a USB Stick With Every BigWeff Video on it", imageUrl: `${URL}usb.webp` },
  { name: "a Cooking Pot Signed by Tegberen", imageUrl: `${URL}cookingpot.webp` },
  { name: "a Piano Signed by John Rei", imageUrl: `${URL}johnrei.webp` },
  { name: "an Omnitrix", imageUrl: `${URL}omnitrix.webp` },
  { name: "a Large 3-Topping Pizza From Domino's", imageUrl: `${URL}pizza.webp` },
  { name: "a Fire Gem", imageUrl: `${URL}firegem.webp` },
  { name: "a Hat Worn and Signed by Cinn", imageUrl: `${URL}cinn.webp` },
  { name: "a Plastic Straw Used by Salamander", imageUrl: `${URL}drinking_straw.webp` },
  { name: "a Collection of Kaploop's Cool Rocks", imageUrl: `${URL}rock_collection.webp` },
  { name: "an Arcle Signed by Evolto", imageUrl: `${URL}evolto.webp` },
  { name: "Mothmad's Frog Hat", imageUrl: `${URL}frog_hat.webp` },
  { name: "a Copy of the Book of the Dead", imageUrl: `${URL}book_dead.webp` },
  { name: "the Sphinx of Hatshepsut", imageUrl: `${URL}sphinx.webp` },
  { name: "A Statue of Lamassu", imageUrl: `${URL}lamassu.webp` },
  { name: "Nike (Winged Victory) of Samothrace", imageUrl: `${URL}nike.webp` },
  { name: "Augustus of Prima Porta", imageUrl: `${URL}augustus.webp` },
  { name: "a Terracotta Krater", imageUrl: `${URL}main-image.webp` },
  { name: "a Terracotta Lekythos", imageUrl: `${URL}terracotta_lekythos.webp` },
  { name: "a Cycladic Figurine", imageUrl: `${URL}cycladic_figure.webp` },
  { name: "the Alexander Mosaic", imageUrl: `${URL}mosaic.webp` },
  { name: "the Ishtar Gate", imageUrl: `${URL}ishtar.webp` },
  { name: "The Standard of Ur", imageUrl: `${URL}standard_of_ur.webp` },
  { name: "a Statue of Ganesha", imageUrl: `${URL}ganesha.webp` },
  { name: "a Statue of Vishnu Riding on Garuda", imageUrl: `${URL}vishnu.webp` },
  { name: "a Pterodactyl Dinosaur Chicken Nugget", imageUrl: `${URL}pterodactyl_nugget.webp` },
  { name: "a T-Rex Dinosaur Chicken Nugget", imageUrl: `${URL}trex_nugget.webp` },
  { name: "a Stegosaurus Dinosaur Chicken Nugget", imageUrl: `${URL}stegosaurus_nugget.webp` },
  { name: "a Brontosaurus Dinosaur Chicken Nugget", imageUrl: `${URL}bronot_nugget.webp` },
  { name: "a Triceratops Dinosaur Chicken Nugget", imageUrl: `${URL}triceraptos_nugget.webp` },
  { name: "a chess set signed by T. Wang", imageUrl: `${URL}chessset.webp` },
  { name: "BrotherDavid's Clay Yokai Scupltures", imageUrl: `${URL}yokai.webp`}
];

module.exports = {
	data: new SlashCommandBuilder()
		.setName('dig')
		.setDescription('me olmec, you dig'),
  
	async execute(interaction: any) {
	await interaction.deferReply();
	
	try {
	
		const isPokemon = Math.random() < 0.005;
		
		if (isPokemon) {
			const pokemonId = pokemonFossilIds[Math.floor(Math.random() * pokemonFossilIds.length)];
			const randomWeight = Math.floor(Math.random() * 1000) + 1;
			const pokeData = await fetchPokeAPI(`https://pokeapi.co/api/v2/pokemon/${pokemonId}`) as PokeAPIResponse;
			const imageUrl = pokeData.sprites.other['official-artwork'].front_shiny;
			const pokemonName = pokeData.name.charAt(0).toUpperCase() + pokeData.name.slice(1);

	        try {
	          await savePokemonCatch(interaction.user.id, {
	            pokemonId,
	            pokemonName,
	            weight: randomWeight,
	            imageUrl,
	            caughtAt: new Date()
	          });
	        } catch (dbError) {
	          console.error('Failed to save Pokémon to database:', dbError);
	        }

			if (!imageUrl) {
				return interaction.editReply(`Super rare mythical pull. You caught a shiny ${pokemonName}! It weighs ${randomWeight}kg <:pog:1416513137536008272>`);
			}
			

			return interaction.editReply({
				content: `Super rare mythical pull. You caught a shiny ${pokemonName}! It weighs ${randomWeight}kg <:pog:1416513137536008272>`,
				files: [imageUrl]
			});
		
		} else {
			// check treasure list
          

			const isTreasure = Math.random() < TREASURE_RATE;
      if (isTreasure) {
        const treasure = treasureList[Math.floor(Math.random() * treasureList.length)];
        const randomPrice = Math.floor(Math.random() * 100000) + 1;
        
        return interaction.editReply({
          content: `Wow a rare treasure!!! You unearthed ${treasure.name}, it is valued at $${randomPrice}! <:pog:1416513137536008272>`,
          files: [treasure.imageUrl]
        });
      }
      // check dino list and fetch wiki image code
			const dino = dinoList[Math.floor(Math.random() * dinoList.length)];
			
			const searchData = await fetchWikipedia(
				`https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=${encodeURIComponent(dino)}&format=json`
			) as WikiSearchResult;
			
			if (!searchData.query?.search?.[0]) {
				return interaction.editReply( `You could not unearthe the fossil and revived it ...`);
			}
			
			const pageId = searchData.query.search[0].pageid;
			const pageData = await fetchWikipedia(
				`https://en.wikipedia.org/w/api.php?action=query&pageids=${pageId}&prop=pageimages&piprop=original|thumbnail&pithumbsize=800&format=json`
			) as WikiPageResult;
			
            const randomWeight = Math.floor(Math.random() * 50001) + 50000;
			const page = pageData.query.pages[pageId];
			const imageUrl = page.thumbnail?.source || page.original?.source;
            
			if (!imageUrl) {
				return interaction.editReply( `You unearthed a fossil and revived it into a ${dino}! It weighs ${randomWeight}kg`);
			}

			const fileSize = await getFileSize(imageUrl);
			const MAX_SIZE = 25 * 1024 * 1024; //25mb
			
			if (fileSize > MAX_SIZE) {
				console.log(`img error`);
				return interaction.editReply({
				content: `You unearthed a fossil and revived it into a ${dino}! It weighs ${randomWeight}kg`,
				});
			}
			

			return interaction.editReply({
				content:  `You unearthed a fossil and revived it into a ${dino}! It weighs ${randomWeight}kg`,
				files: [imageUrl]
			});
		}
		
	} catch (err) {
		console.error(err);
		return interaction.editReply("error no fossil");
	}
	}
};

// helper see /fish
function getFileSize(url: string): Promise<number> {
  return new Promise((resolve, reject) => {
    https.get(url, { method: 'HEAD' }, (res) => {
      const size = parseInt(res.headers['content-length'] || '0', 10);
      resolve(size);
    }).on('error', reject);
  });
}

function fetchWikipedia(url) {
  return new Promise((resolve, reject) => {
    const options = {
      headers: {
        'User-Agent': 'discord bot - dig command'
      }
    };
    https.get(url, options, (res) => {
      let data = '';
      res.on('data', (chunk) => data += chunk);
      res.on('end', () => {
        try {
          resolve(JSON.parse(data));
        } catch (e) {
          reject(e);
        }
      });
    }).on('error', reject);
  });
}

function fetchPokeAPI(url: string): Promise<unknown> {
  return new Promise((resolve, reject) => {
    const options = {
      headers: {
        'User-Agent': 'discord bot - dig command'
      }
    };
    https.get(url, options, (res) => {
      let data = '';
      res.on('data', (chunk) => data += chunk);
      res.on('end', () => {
        try {
          resolve(JSON.parse(data));
        } catch (e) {
          reject(e);
        }
      });
    }).on('error', reject);
  });
}
