const { SlashCommandBuilder } = require('discord.js');
const https = require('https');
// add ifaces
interface WikiSearchResult {
  query?: {
    search?: Array<{ pageid: number }>;
  };
}

interface WikiPageResult {
  query: {
    pages: {
      [key: string]: {
        original?: {
          source: string;
        };
      };
    };
  };
}

module.exports = {
  data: new SlashCommandBuilder()
    .setName('fish')
    .setDescription('me olmec, you fish'),
  
  async execute(interaction: any) {
    const fishList = [
        "African glass catfish",
      	"African lungfish",
      	"Aholehole",
      	"Airbreathing catfish",
      	"Airsac catfish",
      	"Alaska blackfish",
      	"Albacore",
      	"Alewife",
      	"Alfonsino",
      	"Alligatorfish",
      	"Alligator gar",
      	"Amberjack",
      	"American sole",
      	"Amur pike",
      	"Anchovy",
      	"Anemonefish",
      	"Angelfish",
      	"Angler",
      	"Angler catfish",
      	"Anglerfish",
      	"Antarctic cod",
      	"Antarctic icefish",
      	"Antenna codlet",
      	"Arapaima",
      	"Archerfish",
      	"Arctic char",
      	"Armored gurnard",
      	"Armored searobin",
      	"Armorhead",
      	"Armorhead catfish",
      	"Armoured catfish",
      	"Arowana",
      	"Arrowtooth eel",
      	"Asian carp",
      	"Asiatic glassfish",
      	"Atka mackerel",
      	"Atlantic bonito",
      	"Atlantic cod",
      	"Atlantic herring",
      	"Atlantic salmon",
      	"Atlantic saury",
      	"Atlantic sharpnose shark",
      	"Atlantic silverside",
      	"Australasian salmon",
      	"Australian grayling",
      	"Australian herring",
      	"Australian lungfish",
      	"Australian prowfish",
      	"Ayu",
      	"Baikal oilfish",
      	"Bala shark",
      	"Ballan wrasse",
      	"Bamboo shark",
      	"Banded killifish",
      	"Bandfish",
      	"Bangus",
      	"Banjo",
      	"Banjo catfish",
      	"Barb",
      	"Barbel",
      	"Barbeled dragonfish",
      	"Barbeled houndshark",
      	"Barbel-less catfish",
      	"Barfish",
      	"Barracuda",
      	"Barracudina",
      	"Barramundi",
      	"Barred danio",
      	"Barreleye",
      	"Basking shark",
      	"Bass",
      	"Basslet",
      	"Bat ray",
      	"Batfish",
      	"Beachsalmon",
      	"Beaked salmon",
      	"Beaked sandfish",
      	"Beardfish",
      	"Beluga sturgeon",
      	"Bengal danio",
      	"Betta",
      	"Bichir",
      	"Bicolor goat fish",
      	"Bigeye",
      	"Bigeye squaretail",
      	"Bighead carp",
      	"Bigmouth buffalo",
      	"Bigscale",
      	"Bigscale pomfret",
      	"Billfish",
      	"Bitterling",
      	"Black angelfish",
      	"Black bass",
      	"Black dragonfish",
      	"Black mackerel",
      	"Black neon tetra",
      	"Black scabbardfish",
      	"Black scalyfin",
      	"Black sea bass",
      	"Black swallower",
      	"Black tetra",
      	"Black triggerfish",
      	"Blackchin",
      	"Blackfin tuna",
      	"Blackfish",
      	"Blacktip reef shark",
      	"Bleak",
      	"Blenny",
      	"Blind goby",
      	"Blind shark",
      	"Blobfish",
      	"Blowfish",
      	"Blue catfish",
      	"Blue danio",
      	"Blue eye trevalla",
      	"Blue shark",
      	"Blue triggerfish",
      	"Blue whiting",
      	"Blue-redstripe danio",
      	"Bluefin tuna",
      	"Bluefish",
      	"Bluegill",
      	"Blue gourami",
      	"Bluntnose knifefish",
      	"Bluntnose minnow",
      	"Boafish",
      	"Boarfish",
      	"Bobtail snipe eel",
      	"Bocaccio",
      	"Boga",
      	"Bombay duck",
      	"Bonefish",
      	"Bonito",
      	"Bonnethead shark",
      	"Bonnetmouth",
      	"Bonytail",
      	"Bonytongue",
      	"Bowfin",
      	"Boxfish",
      	"Bramble shark",
      	"Bream",
      	"Brill",
      	"Bristlemouth",
      	"Bristlenose catfish",
      	"Broadband dogfish",
      	"Bronze corydoras",
      	"Brook lamprey",
      	"Brook stickleback",
      	"Brook trout",
      	"Brotula",
      	"Brown trout",
      	"Buffalo fish",
      	"Bull shark",
      	"Bull trout",
      	"Bullhead",
      	"Bullhead shark",
      	"Bumblebee goby",
      	"Burbot",
      	"Buri",
      	"Burma danio",
      	"Burrowing goby",
      	"Butterfish",
      	"Butterfly ray",
      	"Butterflyfish",
      	"California flyingfish",
      	"California halibut",
      	"Canary rockfish",
      	"Candiru",
      	"Candlefish",
      	"Capelin",
      	"Cardinal tetra",
      	"Cardinalfish",
      	"Carp",
      	"Carpetshark",
      	"Carpsucker",
      	"Cat shark",
      	"Catalufa",
      	"Catfish",
      	"Catla",
      	"Cavefish",
      	"Celebes rainbowfish",
      	"Central mudminnow",
      	"Chain pickerel",
      	"Channel bass",
      	"Channel catfish",
      	"Char",
      	"Cherry salmon",
      	"Chimaera",
      	"Chinook salmon",
      	"Cherubfish",
      	"Chub",
      	"Chubsucker",
      	"Chum salmon",
      	"Cichlid",
      	"Cisco",
      	"Climbing catfish",
      	"Climbing gourami",
      	"Climbing perch",
      	"Clingfish",
      	"Clown loach",
      	"Clown triggerfish",
      	"Clownfish",
      	"Cobbler",
      	"Cobia",
      	"Cod",
      	"Codlet",
      	"Codling",
      	"Coelacanth",
      	"Coffinfish",
      	"Coho salmon",
      	"Coley",
      	"Collared carpetshark",
      	"Collared dogfish",
      	"Colorado squawfish",
      	"Combfish",
      	"Combtail gourami",
      	"Combtooth blenny",
      	"Common carp",
      	"Common tunny",
      	"Conger eel",
      	"Convict blenny",
      	"Convict cichlid",
      	"Cookiecutter shark",
      	"Coolie loach",
      	"Cornetfish",
      	"Cow shark",
      	"Cowfish",
      	"Cownose ray",
      	"Crappie",
      	"Creek chub",
      	"Crestfish",
      	"Crevice kelpfish",
      	"Croaker",
      	"Crocodile icefish",
      	"Crocodile shark",
      	"Crucian carp",
      	"Cuckoo wrasse",
      	"Cusk",
      	"Cusk-eel",
      	"Cutlassfish",
      	"Cutthroat eel",
      	"Cutthroat trout",
      	"Dab",
      	"Dace",
      	"Daggertooth pike conger",
      	"Damselfish",
      	"Danio",
      	"Dartfish",
      	"Dealfish",
      	"Death Valley pupfish",
      	"Deep-sea eel",
      	"Deep-sea smelt",
      	"Deepwater cardinalfish",
      	"Deepwater flathead",
      	"Deepwater stingray",
      	"Delta smelt",
      	"Demoiselle",
      	"Denticle herring",
      	"Desert pupfish",
      	"Devario",
      	"Devil ray",
      	"Dhufish",
      	"Discus",
      	"Dogfish",
      	"Dogfish shark",
      	"Dogteeth tetra",
      	"Dojo loach",
      	"Dolly Varden trout",
      	"Dolphin fish",
      	"Dorab wolf-herring",
      	"Dorado",
      	"Dory",
      	"Dottyback",
      	"Dragon goby",
      	"Dragonet",
      	"Dragonfish",
      	"Driftfish",
      	"Driftwood catfish",
      	"Drum",
      	"Duckbill",
      	"Duckbill eel",
      	"Dusky grouper",
      	"Dusky shark",
      	"Dwarf gourami",
      	"Dwarf loach",
      	"Eagle ray",
      	"Earthworm eel",
      	"Eel",
      	"Eel cod",
      	"Eel-goby",
      	"Eelpout",
      	"Eeltail catfish",
      	"Elasmobranch",
      	"Electric catfish",
      	"Electric eel",
      	"Electric knifefish",
      	"Electric ray",
      	"Elephant fish",
      	"Elephantnose fish",
      	"Elver",
      	"Ember parrotfish",
      	"Emerald catfish",
      	"Emperor",
      	"Emperor angelfish",
      	"Emperor bream",
      	"Escolar",
      	"Eucla cod",
      	"Eulachon",
      	"European chub",
      	"European eel",
      	"European flounder",
      	"European minnow",
      	"European perch",
      	"False brotula",
      	"False cat shark",
      	"False moray",
      	"False trevally",
      	"Fangtooth",
      	"Fathead sculpin",
      	"Featherback",
      	"Fierasfer",
      	"Filefish",
      	"Finback cat shark",
      	"Fingerfish",
      	"Fire bar danio",
      	"Fire goby",
      	"Firefish",
      	"Flabby whale fish",
      	"Flagblenny",
      	"Flagfin",
      	"Flagfish",
      	"Flagtail",
      	"Flashlight fish",
      	"Flatfish",
      	"Flathead",
      	"Flathead catfish",
      	"Flier",
      	"Flounder",
      	"Flying fish",
      	"Flying gurnard",
      	"Footballfish",
      	"Forehead brooder",
      	"Four-eyed fish",
      	"French angelfish",
      	"Freshwater eel",
      	"Freshwater hatchetfish",
      	"Freshwater shark",
      	"Frigate mackerel",
      	"Frilled shark",
      	"Frogfish",
      	"Frogmouth catfish",
      	"Fusilier fish",
      	"Galjoen fish",
      	"Ganges shark",
      	"Gar",
      	"Garden eel",
      	"Garibaldi",
      	"Garpike",
      	"Ghost fish",
      	"Ghost flathead",
      	"Ghost knifefish",
      	"Ghost pipefish",
      	"Ghost shark",
      	"Ghoul",
      	"Giant danio",
      	"Giant gourami",
      	"Giant sea bass",
      	"Gibberfish",
      	"Gila trout",
      	"Gizzard shad",
      	"Glass catfish",
      	"Glass knifefish",
      	"Glassfish",
      	"Glowlight danio",
      	"Goatfish",
      	"Goblin shark",
      	"Goby",
      	"Golden dojo",
      	"Golden loach",
      	"Golden shiner",
      	"Golden trout",
      	"Goldeye",
      	"Goldfish",
      	"Gombessa",
      	"Goosefish",
      	"Gopher rockfish",
      	"Gourami",
      	"Grass carp",
      	"Graveldiver",
      	"Gray mullet",
      	"Gray reef shark",
      	"Grayling",
      	"Great white shark",
      	"Green spotted puffer",
      	"Green swordtail",
      	"Greeneye",
      	"Greenling",
      	"Grenadier",
      	"Ground shark",
      	"Grouper",
      	"Grunion",
      	"Grunt",
      	"Grunt sculpin",
      	"Grunter",
      	"Gudgeon",
      	"Guitarfish",
      	"Gulf menhaden",
      	"Gulper",
      	"Gulper eel",
      	"Gunnel",
      	"Guppy",
      	"Gurnard",
      	"Haddock",
      	"Hagfish",
      	"Hairtail",
      	"Hake",
      	"Halfbeak",
      	"Halfmoon",
      	"Halibut",
      	"Halosaur",
      	"Hamlet",
      	"Hammerhead shark",
      	"Hammerjaw",
      	"Handfish",
      	"Hardhead catfish",
      	"Harelip sucker",
      	"Hatchetfish",
      	"Hawkfish",
      	"Herring",
      	"Herring smelt",
      	"Hickory Shad",
      	"Hillstream loach",
      	"Hog sucker",
      	"Hoki",
      	"Horn shark",
      	"Horsefish",
      	"Houndshark",
      	"Huchen",
      	"Humuhumunukunukuapua'a",
      	"Hussar",
      	"Icefish",
      	"Ide",
      	"Ilish",
      	"Inanga",
      	"Inconnu",
      	"Jack",
      	"Jack Dempsey",
      	"Jackfish",
      	"Japanese eel",
      	"Javelin",
      	"Jawfish",
      	"Jellynose fish",
      	"Jewel tetra",
      	"Jewelfish",
      	"Jewfish",
      	"John Dory",
      	"Kafue pike",
      	"Kahawai",
      	"Kaluga",
      	"Kanyu",
      	"Kelp perch",
      	"Kelpfish",
      	"Killifish",
      	"King of the herrings",
      	"King-of-the-salmon",
      	"Kingfish",
      	"Kissing gourami",
      	"Knifefish",
      	"Knifejaw",
      	"Koi",
      	"Kokanee",
      	"Kokopu",
      	"Kuhli loach",
      	"Labyrinth fish",
      	"Ladyfish",
      	"Lake chub",
      	"Lake trout",
      	"Lake whitefish",
      	"Lampfish",
      	"Lamprey",
      	"Lancetfish",
      	"Lanternfish",
      	"Largemouth bass",
      	"Leaffish",
      	"Leatherjacket",
      	"Lefteye flounder",
      	"Lemon shark",
      	"Lemon sole",
      	"Lemon tetra",
      	"Lenok",
      	"Leopard danio",
      	"Lightfish",
      	"Limia",
      	"Lined sole",
      	"Ling",
      	"Ling cod",
      	"Lionfish",
      	"Livebearer",
      	"Lizardfish",
      	"Loach",
      	"Loach catfish",
      	"Loach goby",
      	"Loach minnow",
      	"Longfin",
      	"Longfin dragonfish",
      	"Longfin escolar",
      	"Longfin smelt",
      	"Long-finned char",
      	"Long-finned pike",
      	"Long-finned sand diver",
      	"Longjaw mudsucker",
      	"Longneck eel",
      	"Longnose chimaera",
      	"Longnose dace",
      	"Longnose lancetfish",
      	"Longnose sucker",
      	"Longnose whiptail catfish",
      	"Long-whiskered catfish",
      	"Loosejaw",
      	"Lost River sucker",
      	"Louvar",
      	"Loweye catfish",
      	"Luderick",
      	"Luminous hake",
      	"Lumpsucker",
      	"Lungfish",
      	"Mackerel",
      	"Mackerel shark",
      	"Madtom",
      	"Mahi-mahi",
      	"Mahseer",
      	"Mail-cheeked fish",
      	"Mako shark",
      	"Mandarinfish",
      	"Manefish",
      	"Man-of-war fish",
      	"Manta ray",
      	"Marblefish",
      	"Marine hatchetfish",
      	"Marlin",
      	"Masu salmon",
      	"Medaka",
      	"Medusafish",
      	"Megamouth shark",
      	"Menhaden",
      	"Merluccid hake",
      	"Mexican golden trout",
      	"Midshipman fish",
      	"Milkfish",
      	"Minnow",
      	"Minnow of the deep",
      	"Modoc sucker",
      	"Mojarra",
      	"Mola mola",
      	"Monkeyface prickleback",
      	"Monkfish",
      	"Mooneye",
      	"Moonfish",
      	"Moorish idol",
      	"Mora",
      	"Moray eel",
      	"Morid cod",
      	"Morwong",
      	"Moses sole",
      	"Mosquitofish",
      	"Mouthbrooder",
      	"Mozambique tilapia",
      	"Mrigal",
      	"Mud catfish",
      	"Mud minnow",
      	"Mudfish",
      	"Mudskipper",
      	"Mudsucker",
      	"Mullet",
      	"Mummichog",
      	"Murray cod",
      	"Muskellunge",
      	"Mustache triggerfish",
      	"Mustard eel",
      	"Naked-back knifefish",
      	"Nase",
      	"Needlefish",
      	"Neon tetra",
      	"New World rivuline",
      	"New Zealand sand diver",
      	"New Zealand smelt",
      	"Nibble fish",
      	"Noodlefish",
      	"North American darter",
      	"North American freshwater catfish",
      	"North Pacific daggertooth",
      	"Northern anchovy",
      	"Northern clingfish",
      	"Northern lampfish",
      	"Northern pike",
      	"Northern sea robin",
      	"Northern squawfish",
      	"Northern stargazer",
      	"Notothen",
      	"Nurse shark",
      	"Nurseryfish",
      	"Oarfish",
      	"Ocean perch",
      	"Ocean sunfish",
      	"Oceanic whitetip shark",
      	"Oilfish",
      	"Old World knifefish",
      	"Oldwife",
      	"Olive flounder",
      	"Opah",
      	"Opaleye",
      	"Orange roughy",
      	"Orangespine unicorn fish",
      	"Orangestriped triggerfish",
      	"Orbicular batfish",
      	"Orbicular velvetfish",
      	"Oregon chub",
      	"Orfe",
      	"Oriental loach",
      	"Oscar",
      	"Owens pupfish",
      	"Pacific albacore",
      	"Pacific cod",
      	"Pacific hake",
      	"Pacific herring",
      	"Pacific lamprey",
      	"Pacific rudderfish",
      	"Pacific salmon",
      	"Pacific saury",
      	"Pacific trout",
      	"Pacific viperfish",
      	"Paddlefish",
      	"Pancake batfish",
      	"Panga",
      	"Paradise fish",
      	"Parasitic catfish",
      	"Parore",
      	"Parrotfish",
      	"Peacock flounder",
      	"Peamouth",
      	"Pearl danio",
      	"Pearl perch",
      	"Pearleye",
      	"Pearlfish",
      	"Pelagic cod",
      	"Pelican eel",
      	"Pelican gulper",
      	"Pencil catfish",
      	"Pencilfish",
      	"Pencilsmelt",
      	"Peppered corydoras",
      	"Perch",
      	"Peters' elephantnose fish",
      	"Pickerel",
      	"Pigfish",
      	"Pike",
      	"Pike conger",
      	"Pike eel",
      	"Pikeblenny",
      	"Pikeperch",
      	"Pilchard",
      	"Pilot fish",
      	"Pineapplefish",
      	"Pineconefish",
      	"Pink salmon",
      	"Píntano",
      	"Pipefish",
      	"Piranha",
      	"Pirarucu",
      	"Pirate perch",
      	"Plaice",
      	"Platy",
      	"Platyfish",
      	"Pleco",
      	"Plownose chimaera",
      	"Poacher",
      	"Pollock",
      	"Pollyfish",
      	"Pomfret",
      	"Pompano",
      	"Pompano dolphinfish",
      	"Ponyfish",
      	"Popeye catalufa",
      	"Porbeagle shark",
      	"Porcupinefish",
      	"Porgy",
      	"Port Jackson shark",
      	"Powen",
      	"Prickleback",
      	"Pricklefish",
      	"Prickly shark",
      	"Prowfish",
      	"Pufferfish",
      	"Pumpkinseed",
      	"Pupfish",
      	"Pygmy sunfish",
      	"Queen danio",
      	"Queen parrotfish",
      	"Queen triggerfish",
      	"Quillback",
      	"Quillfish",
      	"Rabbitfish",
      	"Raccoon butterfly fish",
      	"Ragfish",
      	"Rainbow trout",
      	"Rainbowfish",
      	"Rasbora",
      	"Ratfish",
      	"Rattail",
      	"Ray",
      	"Razorback sucker",
      	"Razorfish",
      	"Red grouper",
      	"Red salmon",
      	"Red snapper",
      	"Redfin perch",
      	"Redfish",
      	"Redhorse sucker",
      	"Redlip blenny",
      	"Redmouth whalefish",
      	"Redtooth triggerfish",
      	"Red velvetfish",
      	"Red whalefish",
      	"Reedfish",
      	"Reef triggerfish",
      	"Remora",
      	"Requiem shark",
      	"Ribbon eel",
      	"Ribbon sawtail fish",
      	"Ribbonfish",
      	"Rice eel",
      	"Ricefish",
      	"Ridgehead",
      	"Riffle dace",
      	"Righteye flounder",
      	"Rio Grande perch",
      	"River loach",
      	"River shark",
      	"River stingray",
      	"Rivuline",
      	"Roach",
      	"Roanoke bass",
      	"Rock bass",
      	"Rock beauty",
      	"Rock cod",
      	"Rock gunnel",
      	"Rocket danio",
      	"Rockfish",
      	"Rockling",
      	"Rockweed gunnel",
      	"Rohu",
      	"Ronquil",
      	"Roosterfish",
      	"Ropefish",
      	"Rough scad",
      	"Rough sculpin",
      	"Roughy",
      	"Roundhead",
      	"Round herring",
      	"Round stingray",
      	"Round whitefish",
      	"Rudd",
      	"Rudderfish",
      	"Ruffe",
      	"Russian sturgeon",
      	"Sábalo",
      	"Sabertooth",
      	"Saber-toothed blenny",
      	"Sabertooth fish",
      	"Sablefish",
      	"Sacramento blackfish",
      	"Sacramento splittail",
      	"Sailfin silverside",
      	"Sailfish",
      	"Salamanderfish",
      	"Salmon",
      	"Salmon shark",
      	"Sandbar shark",
      	"Sandburrower",
      	"Sand dab",
      	"Sand diver",
      	"Sand eel",
      	"Sandfish",
      	"Sand goby",
      	"Sand knifefish",
      	"Sand lance",
      	"Sandperch",
      	"Sandroller",
      	"Sand stargazer",
      	"Sand tiger",
      	"Sand tilefish",
      	"Sarcastic fringehead",
      	"Sardine",
      	"Sargassum fish",
      	"Sauger",
      	"Saury",
      	"Saw shark",
      	"Sawfish",
      	"Sawtooth eel",
      	"Scabbard fish",
      	"Scaly dragonfish",
      	"Scat",
      	"Scissortail rasbora",
      	"Scorpionfish",
      	"Sculpin",
      	"Scup",
      	"Sea bass",
      	"Sea bream",
      	"Sea catfish",
      	"Sea chub",
      	"Sea devil",
      	"Sea dragon",
      	"Sea lamprey",
      	"Sea raven",
      	"Sea snail",
      	"Sea toad",
      	"Seahorse",
      	"Seamoth",
      	"Searobin",
      	"Sergeant major",
      	"Sevan trout",
      	"Shad",
      	"Shark",
      	"Sharksucker",
      	"Sharpnose puffer",
      	"Sheatfish",
      	"Sheepshead",
      	"Sheepshead minnow",
      	"Shiner",
      	"Shortnose chimaera",
      	"Shortnose sucker",
      	"Shovelnose sturgeon",
      	"Shrimpfish",
      	"Siamese fighting fish",
      	"Sillago",
      	"Silver carp",
      	"Silver dollar",
      	"Silver dory",
      	"Silver hake",
      	"Silverside",
      	"Silvertip tetra",
      	"Sind danio",
      	"Sixgill ray",
      	"Sixgill shark",
      	"Skate",
      	"Skilfish",
      	"Skipjack tuna",
      	"Slender mola",
      	"Slender snipe eel",
      	"Sleeper",
      	"Sleeper shark",
      	"Slickhead",
      	"Slimehead",
      	"Slimy mackerel",
      	"Slimy sculpin",
      	"Slipmouth",
      	"Smalleye squaretail",
      	"Smalltooth sawfish",
      	"Smelt",
      	"Smelt-whiting",
      	"Smooth dogfish",
      	"Snailfish",
      	"Snake eel",
      	"Snake mackerel",
      	"Snakehead",
      	"Snapper",
      	"Snipe eel",
      	"Snipefish",
      	"Snook",
      	"Snubnose eel",
      	"Snubnose parasitic eel",
      	"Sockeye salmon",
      	"Soldierfish",
      	"Sole",
      	"South American darter",
      	"South American lungfish",
      	"Southern Dolly Varden",
      	"Southern flounder",
      	"Southern hake",
      	"Southern sandfish",
      	"Southern smelt",
      	"Spadefish",
      	"Spaghetti eel",
      	"Spanish mackerel",
      	"Spearfish",
      	"Speckled trout",
      	"Spiderfish",
      	"Spikefish",
      	"Spinefoot",
      	"Spiny basslet",
      	"Spiny dogfish",
      	"Spiny dwarf catfish",
      	"Spiny eel",
      	"Spinyfin",
      	"Splitfin",
      	"Spookfish",
      	"Spotted climbing perch",
      	"Spotted danio",
      	"Spottail pinfish",
      	"Sprat",
      	"Springfish",
      	"Squarehead catfish",
      	"Squaretail",
      	"Squawfish",
      	"Squeaker",
      	"Squirrelfish",
      	"Staghorn sculpin",
      	"Stargazer",
      	"Starry flounder",
      	"Steelhead",
      	"Stickleback",
      	"Stingfish",
      	"Stingray",
      	"Stonecat",
      	"Stonefish",
      	"Stoneroller minnow",
      	"Stream catfish",
      	"Striped bass",
      	"Striped burrfish",
      	"Sturgeon",
      	"Sucker",
      	"Suckermouth armored catfish",
      	"Summer flounder",
      	"Sundaland noodlefish",
      	"Sunfish",
      	"Surf sardine",
      	"Surfperch",
      	"Surgeonfish",
      	"Swallower",
      	"Swamp-eel",
      	"Swampfish",
      	"Sweeper",
      	"Swordfish",
      	"Swordtail",
      	"Tadpole cod",
      	"Tadpole fish",
      	"Tailor",
      	"Taimen",
      	"Tang",
      	"Tapetail",
      	"Tarpon",
      	"Tarwhine",
      	"Telescopefish",
      	"Temperate bass",
      	"Temperate ocean-bass",
      	"Temperate perch",
      	"Tench",
      	"Tenpounder",
      	"Tenuis",
      	"Tetra",
      	"Thorny catfish",
      	"Thornfish",
      	"Threadfin",
      	"Threadfin bream",
      	"Thread-tail",
      	"Three spot gourami",
      	"Threespine stickleback",
      	"Three-toothed puffer",
      	"Thresher shark",
      	"Tidewater goby",
      	"Tiger barb",
      	"Tigerfish",
      	"Tigerperch",
      	"Tiger shark",
      	"Tiger shovelnose catfish",
      	"Tilapia",
      	"Tilefish",
      	"Titan triggerfish",
      	"Toadfish",
      	"Tommy ruff",
      	"Tompot blenny",
      	"Tonguefish",
      	"Tope",
      	"Topminnow",
      	"Torpedo",
      	"Torrent catfish",
      	"Torrent fish",
      	"Trahira",
      	"Treefish",
      	"Trevally",
          "Triggerfish",
          "Triplefin blenny",
          "Triplespine",
          "Tripletail",
          "Tripod fish",
          "Trout",
          "Trout cod",
          "Trout-perch",
          "Trumpeter",
          "Trumpetfish",
          "Trunkfish",
          "Tubeblenny",
          "Tube-eye",
          "Tube-snout",
          "Tubeshoulder",
          "Tui chub",
          "Tuna",
          "Turbot",
          "Two spotted goby",
          "Uaru",
          "Unicorn fish",
          "Upside-down catfish",
          "Vanjaram",
          "Velvet belly lanternshark",
          "Velvet catfish",
          "Velvetfish",
          "Vendace",
          "Vermilion snapper",
          "Vimba",
          "Viperfish",
          "Wahoo",
          "Walking catfish",
          "Wallago",
          "Walleye",
          "Walleye pollock",
          "Walu",
          "Warmouth",
          "Warty angler",
          "Waryfish",
          "Waspfish",
          "Weasel shark",
          "Weatherfish",
          "Weever",
          "Weeverfish",
          "Wels catfish",
          "Whale catfish",
          "Whalefish",
          "Whale shark",
          "Whiff",
          "Whitebait",
          "White croaker",
          "Whitefish",
          "White marlin",
          "White shark",
          "Whitetip reef shark",
          "Whiting",
          "Wobbegong",
          "Wolf-eel",
          "Wolffish",
          "Wolf-herring",
          "Worm eel",
          "Wormfish",
          "Wrasse",
          "Wrymouth",
          "X-ray tetra",
          "Yellow-and-black triplefin",
          "Yellowback fusilier",
          "Yellowbanded perch",
          "Yellow bass",
          "Yellowedge grouper",
          "Yellow-edged moray",
          "Yellow-eye mullet",
          "Yellowhead jawfish",
          "Yellowfin croaker",
          "Yellowfin cutthroat trout",
          "Yellowfin grouper",
          "Yellowfin tuna",
          "Yellowfin pike",
          "Yellowfin surgeonfish",
          "Yellow jack",
          "Yellowmargin triggerfish",
          "Yellow moray",
          "Yellow perch",
          "Yellowtail",
          "Yellowtail amberjack",
          "Yellowtail barracuda",
          "Yellowtail clownfish",
          "Yellowtail horse mackerel",
          "Yellowtail kingfish",
          "Yellowtail snapper",
          "Yellow tang",
          "Yellow weaver",
          "Yellowtail catfish",
          "Zander",
          "Zebra bullhead shark",
          "Zebra danio",
          "Zebrafish",
          "Zebra lionfish",
          "Zebra loach",
          "Zebra oto",
          "Zebra pleco",
          "Zebra shark",
          "Zebra tilapia",
          "Swedish fish" // mythical pull
    ];
    
    const fish = fishList[Math.floor(Math.random() * fishList.length)];
    await interaction.deferReply();
    
    try {
      const searchData = await fetchWikipedia(`https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=${encodeURIComponent(fish)}&format=json`) as WikiSearchResult;
      
      if (!searchData.query?.search?.[0]) {
        return interaction.editReply(`dont have the fish`);
      }
      
      const pageId = searchData.query.search[0].pageid;
      const pageData = await fetchWikipedia(`https://en.wikipedia.org/w/api.php?action=query&pageids=${pageId}&prop=pageimages&piprop=original|thumbnail&pithumbsize=800&format=json`) as WikiPageResult;
      const page = pageData.query.pages[pageId];
      const randomWeight = Math.floor(Math.random() * 1000) + 1;
      
      const imageUrl = page.thumbnail?.source || page.original?.source;
      if (!imageUrl) {
        return interaction.editReply(`You caught a ${fish}, it weighs ${randomWeight}kg`);
      }

      const fileSize = await getFileSize(imageUrl);
      const MAX_SIZE = 25 * 1024 * 1024; // try 25 mb
      
      if (fileSize > MAX_SIZE) {
        console.log(`Image too large (${(fileSize / 1024 / 1024).toFixed(2)}MB), sending without image`);
        return interaction.editReply({
          content: `You caught a ${fish}, it weighs ${randomWeight}kg`,
        });
      }
      
      return interaction.editReply({
        content: `You caught a ${fish}, it weighs ${randomWeight}kg`,
        files: [imageUrl]
      });
      
    } catch (err) {
      console.error(err);
      return interaction.editReply("error fish img fetch");
    }
  },
};
//file size checker
function getFileSize(url: string): Promise<number> {
  return new Promise((resolve, reject) => {
    https.get(url, { method: 'HEAD' }, (res) => {
      const size = parseInt(res.headers['content-length'] || '0', 10);
      resolve(size);
    }).on('error', reject);
  });
}
// Helper function to fetch from Wikipedia API
function fetchWikipedia(url) {
  return new Promise((resolve, reject) => {
    const options = {
      headers: {
        'User-Agent': 'discord bot - fish command'
      }
    };
    https.get(url, options, (res) => {
      let data = '';
      res.on('data', (chunk) => data += chunk);
      res.on('end', () => {
        try {
          resolve(JSON.parse(data));
        } catch (e) {
          reject(e);
        }
      });
    }).on('error', reject);
  });
}
